// tools/site_port/build_runtime.cjs · WEB-5 · lib/site/rt/{motion,runtime}.ts into ONE browser script (no React, no
// framework), written to lib/site/rt.gen.ts as a string with its sha256; the site serves it at /site-rt/<sha>.js,
// cached for a year. Run: node tools/site_port/build_runtime.cjs
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.join(__dirname, '..', '..'); const ts = require(path.join(ROOT, 'node_modules/typescript'));
const strip = (s) => s.replace(/^import .*$/gm, '').replace(/^export /gm, '');
const src = strip(fs.readFileSync(path.join(ROOT, 'lib/site/rt/motion.ts'), 'utf8')) + '\n' + strip(fs.readFileSync(path.join(ROOT, 'lib/site/rt/runtime.ts'), 'utf8')) +
  "\n(function () { var H = document.documentElement; if (!H.dataset.style) return; start(H.dataset.style); if (H.dataset.code) beacon(H.dataset.code, H.dataset.page || 'home', H.dataset.look || undefined); })();\n";
const js = ts.transpileModule(src, { compilerOptions: { target: ts.ScriptTarget.ES2019, module: ts.ModuleKind.None, removeComments: true } }).outputText;
const body = '(function(){"use strict";\n' + js + '\n})();\n';
const sha = crypto.createHash('sha256').update(body).digest('hex').slice(0, 16);
fs.writeFileSync(path.join(ROOT, 'lib/site/rt.gen.ts'), `// lib/site/rt.gen.ts · GENERATED by tools/site_port/build_runtime.cjs from lib/site/rt/*.ts. Do not edit; re-run.\nexport const RT_SHA = '${sha}';\nexport const RT_JS = ${JSON.stringify(body)};\n`);
console.log('build_runtime:', body.length, 'bytes, sha', sha);
