// tools/site_port/gen_faces.cjs · WEB-5 · the styles site's faces (CE-47 ruling B: the site serves its own fonts).
// Copies each face the approved prototypes load (WEB-3 build.py FONTS_ALL) from @fontsource into public/site-fonts,
// with each family's licence, and writes lib/site/faces.gen.ts: the files, and the size-matched fallback computed
// from the display file by Next's own routine (next/font/local's getFallbackMetricsFromFontFile, fontkit).
// Run: node tools/site_port/gen_faces.cjs   (reads node_modules/@fontsource/*; prints what it wrote)
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const ROOT = path.join(__dirname, '..', '..');
const fkMod = require(path.join(ROOT, 'node_modules/next/dist/compiled/@next/font/dist/fontkit')).default; const fontFromBuffer = fkMod.default || fkMod;   // next/font/local loader.js:7-8
const { getFallbackMetricsFromFontFile } = require(path.join(ROOT, 'node_modules/next/dist/compiled/@next/font/dist/local/get-fallback-metrics-from-font-file'));
const F = {
  'Bodoni Moda': ['bodoni-moda', [['400', 'normal'], ['400', 'italic'], ['500', 'normal']], 'serif'],
  'Inter Tight': ['inter-tight', [['400', 'normal'], ['500', 'normal']], 'sans-serif'],
  'Cormorant Garamond': ['cormorant-garamond', [['400', 'italic'], ['500', 'normal'], ['500', 'italic']], 'serif'],
  Manrope: ['manrope', [['400', 'normal'], ['500', 'normal']], 'sans-serif'],
  Italiana: ['italiana', [['400', 'normal']], 'serif'], Jost: ['jost', [['300', 'normal'], ['400', 'normal'], ['500', 'normal']], 'sans-serif'],
  Marcellus: ['marcellus', [['400', 'normal']], 'serif'], Mulish: ['mulish', [['400', 'normal'], ['500', 'normal'], ['400', 'italic']], 'sans-serif'],
  Fraunces: ['fraunces', [['300', 'normal'], ['300', 'italic'], ['400', 'italic']], 'serif'], 'Plus Jakarta Sans': ['plus-jakarta-sans', [['400', 'normal'], ['500', 'normal']], 'sans-serif'],
  'Instrument Serif': ['instrument-serif', [['400', 'normal'], ['400', 'italic']], 'serif'], 'Instrument Sans': ['instrument-sans', [['400', 'normal'], ['500', 'normal']], 'sans-serif'],
  'Gilda Display': ['gilda-display', [['400', 'normal']], 'serif'], Figtree: ['figtree', [['300', 'normal'], ['400', 'normal'], ['500', 'normal']], 'sans-serif'],
};
const out = {}; const OUT = path.join(ROOT, 'public/site-fonts'); fs.mkdirSync(OUT, { recursive: true }); const lic = [];
for (const [fam, [pkg, ws, cat]] of Object.entries(F)) {
  const dir = path.join(ROOT, 'node_modules/@fontsource', pkg); const ver = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')).version;
  const files = ws.map(([w, st]) => { const src = path.join(dir, 'files', `${pkg}-latin-${w}-${st}.woff2`); const buf = fs.readFileSync(src);
    const h = crypto.createHash('sha256').update(buf).digest('hex').slice(0, 10); const name = `${pkg}-latin-${w}-${st}.${h}.woff2`;
    fs.writeFileSync(path.join(OUT, name), buf); return { weight: w, style: st, file: `/site-fonts/${name}`, bytes: buf.length }; });
  const reg = ws.find(([, st]) => st === 'normal') || ws[0];
  const m = getFallbackMetricsFromFontFile(fontFromBuffer(fs.readFileSync(path.join(dir, 'files', `${pkg}-latin-${reg[0]}-${reg[1]}.woff2`))), cat);
  const licText = fs.existsSync(path.join(dir, 'LICENSE')) ? fs.readFileSync(path.join(dir, 'LICENSE'), 'utf8') : '';
  fs.writeFileSync(path.join(OUT, `${pkg}.LICENSE.txt`), licText);
  lic.push(`${fam}\t@fontsource/${pkg}@${ver}\t${(JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')).license) || '?'}`);
  out[fam] = { pkg, version: ver, category: cat, files, fallback: m };
}
fs.writeFileSync(path.join(OUT, 'SOURCES.txt'), 'public/site-fonts · WEB-5 · the styles site\'s faces, copied from @fontsource (exact versions below) by tools/site_port/gen_faces.cjs.\nEach family\'s licence sits beside its files as <package>.LICENSE.txt.\n\n' + lic.join('\n') + '\n');
fs.writeFileSync(path.join(ROOT, 'lib/site/faces.gen.ts'), `// lib/site/faces.gen.ts · GENERATED by tools/site_port/gen_faces.cjs. Do not edit; re-run the tool.\n// Every face the approved styles draw, its file under public/site-fonts (content-hashed names, cached for a year),\n// and the size-matched fallback computed from the file by next/font/local's own routine.\nexport type Face = { pkg: string; version: string; category: string; files: { weight: string; style: string; file: string; bytes: number }[];\n  fallback: { fallbackFont: string; ascentOverride: string; descentOverride: string; lineGapOverride: string; sizeAdjust: string } };\nexport const FACES: Record<string, Face> = ${JSON.stringify(out, null, 1)};\n`);
console.log('gen_faces:', Object.keys(out).length, 'families,', Object.values(out).reduce((a, f) => a + f.files.length, 0), 'files;', lic.map((l) => l.split('\t').slice(1).join(' ')).join('; '));
