# tools/site_port/port_css.py · WEB-5 · the approved renditions' CSS, carried verbatim into the renderer.
# Source: WEB-3's handoff (WEB3_handoff_prototypes_benches.zip sha256 6d444afa3ee3...), copied beside this file.
# For each style the CSS between the prototype's placeholders and </style> is written to lib/site/styles/<style>.css.ts
# with the sha256 of the source file, so the chair can prove the port changed nothing. Bare run: writes and prints.
import hashlib, os, re
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, '..', '..', 'lib', 'site', 'styles')
def emit(name, css, src):
    sha = hashlib.sha256(open(src, 'rb').read()).hexdigest()
    body = css.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    open(os.path.join(OUT, f'{name}.css.ts'), 'w').write(
        f"// lib/site/styles/{name}.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.\n"
        f"// Source: tools/site_port/{os.path.basename(src)} sha256 {sha} (WEB-3's approved rendition, verbatim).\n"
        f"export const CSS = `{body}`;\n")
    print(f'{name}: {len(css)} bytes from {os.path.basename(src)} {sha[:12]}')
emit('engine', open(os.path.join(HERE, 'engine.css')).read(), os.path.join(HERE, 'engine.css'))
for st in ['gallery', 'noir', 'heritage', 'aurora', 'riviera']:
    s = open(os.path.join(HERE, f'{st}.html')).read()
    css = s.split('__BASECSS__', 1)[1].split('</style>', 1)[0]
    emit(st, css, os.path.join(HERE, f'{st}.html'))
s = open(os.path.join(HERE, 'couture.html')).read()           # Couture carries its own base (not on engine.css)
css = s.split('__FONTS__', 1)[1].split('</style>', 1)[0]
emit('couture', css, os.path.join(HERE, 'couture.html'))
