'use client';
// MomentsRoom — the photo diary bloom.
//
// TDW_13 · D-4 · VERBATIM RELOCATION. This component's body is byte-identical to
// the lines it occupied in sanctuary/page.tsx at b1448c4. Only the import
// mechanism changed: the symbols it used to reach at module scope it now names
// at the top of its own file. No token conversion, no hygiene, no feature —
// those are P3 and P5 and they do not ride a relocation commit (F-1).

import React, { useState, useRef, useEffect } from 'react';
import { FT, FS, FI, getCoupleIdForFrost } from '@/lib/frost/tokens';
import { coupleAccessToken } from '@/components/frost/_shared/coupleAccessToken';
// ── TDW_15 P3.3 · THE 07 IMAGE DISCIPLINE, ADOPTED NOT RE-IMPLEMENTED ────────
// `lib/img.ts` is the ONE home for Cloudinary delivery (card w_800 · thumb w_200
// · full w_1600 · LQIP w_24,e_blur:1000, each with q_auto/f_auto), addressed at
// the two paths the 07 spec names. Four surfaces already ride it —
// blooms/discover.tsx, blooms/muse.tsx, the sanctuary conductor and
// vendor/portfolio — and this bloom was the last frost image surface that did
// not. No variant is added here and no second table is written; that is the
// whole of the spec's "nothing clever".
//
// READ THE PASS-THROUGH RULE BEFORE TRUSTING EITHER CALL: both helpers transform
// ONLY when the segment after `/image/upload/` is `v<digits>`, and return any
// other URL BYTE-UNCHANGED. So a moment whose `image_url` is not a canonical
// Cloudinary upload renders exactly as it does today — this delivery cannot
// break a row it does not recognise, which is why the adoption is safe to make
// unconditionally rather than behind a shape test of its own.
//
// ── THE TWO LINES BELOW ARE RULED EDITS TO A VERBATIM RELOCATION (R-35.25) ───
// This file is a D-4 relocation under F-1 and `scripts/tdw13_d4_extraction`
// holds every relocated line. The two `<img src>` sites this limb rewrites are
// the NINTH and TENTH entries of that canary's allowlist, granted by R-35.25 and
// labelled there one at a time. An ELEVENTH eaten line still reddens it. If you
// are about to edit a third line in this file, you need a ruling first — that is
// the property, not an obstacle.
import { imgUrl, lqipUrl } from '@/lib/frost-api/img';


// ── MOMENTS ROOM ──────────────────────────────────────────────────────────────
// Ornament string — photo thumbnails hanging off a vertical line.
// Left: thumbnail (56×56, tappable → full bleed).
// Right: date + day count + caption.
// Full-bleed on tap. Circle badge when contributed by a member.
// Caption: auto-generated by Vision→Haiku on WhatsApp forwards.

interface MomentPhoto { id:string; save_number:number; image_url:string; caption?:string|null; saved_by_role:string; created_at:string; }

interface MomentsRoomProps { dark:boolean; accent:string; }

export function MomentsRoom({ dark, accent }: MomentsRoomProps) {
  const [moments,   setMoments]   = React.useState<MomentPhoto[]>([]);
  const [loading,   setLoading]   = React.useState(true);
  const [fullImg,   setFullImg]   = React.useState<string|null>(null);
  const [uploading, setUploading] = React.useState(false);
  const [toast,     setToast]     = React.useState('');
  // Caption editing
  const [editingId,   setEditingId]   = React.useState<string|null>(null);
  const [editCaption, setEditCaption] = React.useState('');
  const [savingCap,   setSavingCap]   = React.useState(false);
  const fileRef = React.useRef<HTMLInputElement>(null);
  const API = process.env.NEXT_PUBLIC_API_BASE||'https://dream-os-production.up.railway.app';

  const showToast = (msg:string) => { setToast(msg); setTimeout(()=>setToast(''),2500); };

  const saveCaption = async (id:string) => {
    setSavingCap(true);
    try {
      const token = coupleAccessToken();
      const res = await fetch(`${API}/api/v2/couple/muse/caption/${id}`,{
        method:'PATCH',
        headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json'},
        body:JSON.stringify({caption:editCaption.trim()||null}),
      });
      if(res.ok) {
        setMoments(prev=>prev.map(m=>m.id===id?{...m,caption:editCaption.trim()||null}:m));
        showToast('Caption saved.');
      } else {
        showToast('Could not save. Try again.');
      }
    } catch { showToast('Could not save. Try again.'); }
    setSavingCap(false);
    setEditingId(null);
  };

  // Get days at the time a moment was created
  function daysAtCapture(iso:string, weddingIso:string|null):string|null {
    if(!weddingIso) return null;
    const wedding = new Date(weddingIso).getTime();
    const saved   = new Date(iso).getTime();
    const diff    = Math.round((wedding - saved) / 86400000);
    if(diff < 0)  return 'After the wedding';
    if(diff === 0) return 'Wedding day';
    return `Day ${diff}`;
  }

  const weddingIso = React.useMemo(()=>{
    try {
      const raw = localStorage.getItem('couple_session')||localStorage.getItem('couple_web_session');
      if(raw) { const s=JSON.parse(raw); return s?.wedding_date||null; }
    } catch {} return null;
  },[]);

  React.useEffect(()=>{
    const load = async () => {
      try {
        // F-07.70: the `if(!raw)` guard is subsumed by the guard below, which sets
        // the same loading state and turns away the same brides.
        const coupleId = getCoupleIdForFrost();
        const token = coupleAccessToken();
        if(!coupleId||!token){setLoading(false);return;}
        const res = await fetch(`${API}/api/v2/couple/moments/${coupleId}`,{headers:{Authorization:`Bearer ${token}`}});
        if(!res.ok){setLoading(false);return;}
        const data = await res.json();
        setMoments(data.moments||[]);
      } catch(e){ console.error(e); }
      finally{ setLoading(false); }
    };
    load();
  },[]);

  const handleFiles = async (e:React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files||[]).filter((f:File)=>f.type.startsWith('image/')) as File[];
    if(!files.length) return;
    setUploading(true);
    // F-07.70: the blob guard is KEPT — it carries its own distinct copy and is
    // this caller's only "is she signed in" test.
    const raw = localStorage.getItem('couple_session')||localStorage.getItem('couple_web_session');
    if(!raw){showToast('Please log in to add moments.');setUploading(false);return;}
    const token = coupleAccessToken();
    // F-07.70 · THE PARITY BYTE, founder-ruled unconditionally at charter. This
    // site spoke a bare twin of a sentence four sibling sites speak whole
    // ((auth)/couple/onboarding:122,:154 · (frost)/canvas/onboarding:85,:126).
    // The byte below is theirs, byte-identical — moved, never re-authored.
    if(!token){showToast('Session expired. Please sign in again.');setUploading(false);return;}
    let added = 0;
    for(const file of files){
      try {
        const b64 = await new Promise<string>((res,rej)=>{
          const r=new FileReader(); r.onload=()=>res((r.result as string).split(',')[1]); r.onerror=rej; r.readAsDataURL(file);
        });
        const resp = await fetch(`${API}/api/v2/couple/muse/upload`,{
          method:'POST',
          headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json'},
          body:JSON.stringify({image_base64:b64,mime_type:file.type,surface:'moments'}),
        });
        const data = await resp.json();
        if(data.ok&&data.save){ setMoments(prev=>[data.save,...prev]); added++; }
      } catch{}
    }
    if(fileRef.current) fileRef.current.value='';
    setUploading(false);
    showToast(added===0?'Could not add. Try again.':added===1?'Moment saved.':`${added} moments saved.`);
  };

  function fmtDate(iso:string):string {
    return new Date(iso).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
  }

  const ink     = '#F0EDE8';
  const inkMute = 'rgba(240,237,232,.35)';
  const line    = 'rgba(240,237,232,.08)';
  const accent2 = '#C4856A';

  return (
    <div style={{flex:1,display:'flex',flexDirection:'column',background:'#080608',position:'relative',overflow:'hidden'}}>
      {toast&&<div style={{position:'fixed',top:'calc(env(safe-area-inset-top,0px)+16px)',left:'50%',transform:'translateX(-50%)',background:'rgba(240,237,232,.95)',color:'#080608',fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',textTransform:'uppercase' as any,padding:'8px 18px',borderRadius:20,zIndex:400,pointerEvents:'none',whiteSpace:'nowrap'}}>{toast}</div>}

      {/* Full-screen viewer */}
      {fullImg&&<div onClick={()=>setFullImg(null)} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.96)',zIndex:500,display:'flex',alignItems:'center',justifyContent:'center'}}>
        {/* R-35.25 · NINTH ENTRY. `full` (w_1600) rather than the raw original:
            the viewer is a phone screen and the original can be several megabytes
            of camera JPEG. */}
        <img src={imgUrl(fullImg,'full')} alt="" style={{maxWidth:'96vw',maxHeight:'92vh',objectFit:'contain',borderRadius:4}}/>
        <button onClick={()=>setFullImg(null)} style={{position:'absolute',top:24,right:20,background:'rgba(240,237,232,.12)',border:'none',borderRadius:20,width:36,height:36,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',color:'rgba(240,237,232,.8)',fontSize:18}}>✕</button>
      </div>}

      {/* Header */}
      <div style={{padding:'20px 18px 12px',flexShrink:0,display:'flex',alignItems:'flex-end',justifyContent:'space-between',borderBottom:`0.5px solid ${line}`}}>
        <div>
          <div style={{fontFamily:"'Italianno',cursive",fontSize:46,color:ink,lineHeight:1,marginBottom:2}}>Moments</div>
          <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',textTransform:'uppercase' as any,color:inkMute}}>{loading?'loading…':`${moments.length} saved`}</div>
        </div>
        <button onClick={()=>fileRef.current?.click()} disabled={uploading}
          style={{display:'flex',alignItems:'center',gap:5,padding:'7px 14px',borderRadius:100,
            border:`0.5px solid ${accent2}44`,background:`${accent2}12`,
            fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',
            textTransform:'uppercase' as any,color:accent2,cursor:'pointer',opacity:uploading?.5:1}}>
          {uploading?'Adding…':'+ Add'}
        </button>
      </div>

      {/* Ornament string */}
      <div className="no-scroll" style={{flex:1,overflowY:'auto',WebkitOverflowScrolling:'touch' as any,padding:'20px 0 16px',position:'relative'}}>

        {/* THE STRING IS RETIRED (TDW_09 atelier · Fork 1 arm A). It ran at left:82,
            the exact x of the thumbnail gutter it related to. The gutter is gone with
            the thumbnails; a thread beside nothing is decoration, and the information
            it carried — which photograph belongs to which day — now rides the stamp on
            each plate. Removed rather than re-aimed: there is no column to aim it at. */}

        {loading&&<div style={{padding:48,textAlign:'center' as any,fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',textTransform:'uppercase' as any,color:inkMute}}>loading…</div>}

        {!loading&&moments.length===0&&(
          <div style={{padding:`${FS.s5}px ${FS.gutter}px`,display:'flex',flexDirection:'column',alignItems:'center',gap:FS.s2,textAlign:'center' as any}}>
            <div style={{fontFamily:"'Italianno',cursive",fontSize:46,color:accent2,lineHeight:1}}>Nothing yet.</div>
            <div style={{fontFamily:"'Fraunces',serif",fontStyle:'italic',fontWeight:300,fontSize:16,color:'rgba(240,237,232,.5)',lineHeight:1.7,maxWidth:280,fontFeatureSettings:'"opsz" 9'}}>
              Your first photo becomes Day One. The brunch with the girls, the trial day, the shopping chaos — they all live here.
            </div>
            <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',textTransform:'uppercase' as any,color:inkMute,marginTop:4}}>WhatsApp moments — coming soon</div>
            <button onClick={()=>fileRef.current?.click()}
              style={{marginTop:8,padding:'12px 28px',borderRadius:100,background:accent2,border:'none',
                fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',
                textTransform:'uppercase' as any,color:'#0C0A09',cursor:'pointer'}}>
              Add from camera roll
            </button>
          </div>
        )}

        {moments.map((m,i)=>{
          const isFirst = i===0;
          const dayLabel = daysAtCapture(m.created_at, weddingIso);
          return (
            <div key={m.id} style={{marginBottom:FS.s4,position:'relative',zIndex:2}}>
              {/* ── THE PLATE (TDW_09 atelier · Fork 1 arm A, founder-approved) ────────
                  This was a 54x54 thumbnail at radius 8, hung off an 82px gutter on a
                  vertical thread, with a connector and a dot. A photo diary whose
                  photographs are 54px is a thumbnail list wearing a diary's name.
                  The plate takes the full measure at FI.plateRatio, zero radius.
                  WHAT THE THREAD CARRIED, AND WHERE IT WENT: it related a thumbnail to
                  its date. With no thumbnail column there is nothing for a thread to
                  run beside, so the date rides ON the plate and the day grouping rides
                  the rule above it. The connector, the dot, the 82px gutter and the
                  first-item glow retire together — the `isFirst` accent survives as the
                  stamp's colour, so Day One still announces itself.
                  EVERY CAPABILITY IS KEPT: tap-to-zoom, tap-to-edit caption, inline
                  save/cancel, the Circle chip, the day-label arithmetic. */}
              <div onClick={()=>setFullImg(m.image_url)}
                style={{width:'100%',aspectRatio:FI.plateRatio,borderRadius:FI.plateRadius,overflow:'hidden',
                  cursor:'zoom-in',background:'#1a1714',position:'relative'}}>
                {/* R-35.25 · TENTH ENTRY. The two-layer plate: a few-hundred-byte
                    blurred wash that lands immediately, and the card variant over
                    it — byte-for-byte the pattern blooms/discover.tsx uses at its
                    own plate. What this replaces was a FULL-SIZE ORIGINAL served
                    into a small tile with nothing but `loading="lazy"`: right on
                    wifi, expensive on a phone, and the reason this limb exists. */}
                <img src={lqipUrl(m.image_url)} alt="" aria-hidden draggable={false} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',pointerEvents:'none'}}/>
                <img src={imgUrl(m.image_url,'card')} alt={m.caption||''} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',display:'block'}} loading="lazy"/>
                <div style={{position:'absolute',top:FS.s2,left:FS.gutter,right:FS.gutter,display:'flex',alignItems:'center',gap:FS.s1,pointerEvents:'none'}}>
                  <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:FT.engravedSm,letterSpacing:FS.track,textTransform:'uppercase' as any,color:isFirst?accent2:ink,textShadow:'0 1px 14px rgba(0,0,0,.9)'}}>
                    {fmtDate(m.created_at)}{dayLabel?` · ${dayLabel}`:''}
                  </span>
                  {m.saved_by_role==='circle_member'&&(
                    <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:FT.engravedSm,letterSpacing:FS.track,textTransform:'uppercase' as any,color:accent2,border:`0.5px solid ${accent2}44`,borderRadius:3,padding:'1px 5px',textShadow:'0 1px 14px rgba(0,0,0,.9)'}}>Circle</span>
                  )}
                </div>
              </div>

              <div style={{padding:`${FS.s2}px ${FS.gutter}px 0`}}>
                {/* Caption: show inline editor if editing, else show text + tap-to-edit */}
                {editingId===m.id ? (
                  <div style={{display:'flex',flexDirection:'column',gap:6}}>
                    <input
                      autoFocus
                      value={editCaption}
                      onChange={e=>setEditCaption(e.target.value)}
                      onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();saveCaption(m.id);}if(e.key==='Escape'){setEditingId(null);}}}
                      placeholder="Add a caption…"
                      style={{background:'rgba(240,237,232,.08)',border:`0.5px solid ${accent2}55`,borderRadius:4,
                        padding:'6px 10px',color:'rgba(240,237,232,.9)',
                        fontFamily:"'Fraunces',serif",fontStyle:'italic',fontSize:16,
                        outline:'none',userSelect:'text',WebkitUserSelect:'text' as any}}
                    />
                    <div style={{display:'flex',gap:6}}>
                      <button onClick={()=>saveCaption(m.id)} disabled={savingCap}
                        style={{padding:'4px 10px',borderRadius:4,background:accent2,border:'none',
                          fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',
                          textTransform:'uppercase' as any,color:'#0C0A09',cursor:'pointer',opacity:savingCap?.5:1}}>
                        {savingCap?'Saving…':'Save'}
                      </button>
                      <button onClick={()=>setEditingId(null)}
                        style={{padding:'4px 10px',borderRadius:4,background:'transparent',border:`0.5px solid rgba(240,237,232,.15)`,
                          fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',
                          textTransform:'uppercase' as any,color:inkMute,cursor:'pointer'}}>
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <div onClick={()=>{setEditingId(m.id);setEditCaption(m.caption||'');}}
                    style={{cursor:'text',minHeight:18}}>
                    {m.caption
                      ? <div style={{fontFamily:"'Fraunces',serif",fontStyle:'italic',fontWeight:300,fontSize:16,color:'rgba(240,237,232,.6)',lineHeight:1.55,fontFeatureSettings:'"opsz" 9'}}>{m.caption}</div>
                      : <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',color:'rgba(240,237,232,.22)',textTransform:'uppercase' as any}}>Tap to add caption</div>
                    }
                  </div>
                )}
              </div>
            </div>
          );
        })}

        {!loading&&moments.length>0&&(
          <div style={{padding:'8px 18px 8px 100px',textAlign:'left' as any}}>
            <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:9,letterSpacing:'.22em',textTransform:'uppercase' as any,color:inkMute}}>WhatsApp moments — coming soon</div>
          </div>
        )}

        {/* Bottom vignette */}
        <div style={{position:'absolute',bottom:0,left:0,right:0,height:60,background:'linear-gradient(transparent,rgba(8,6,8,.8))',pointerEvents:'none'}}/>
        <div style={{height:20}}/>
      </div>

      <input ref={fileRef} type="file" accept="image/*" multiple onChange={handleFiles} style={{display:'none'}}/>
    </div>
  );
}
