// lib/site/faces.gen.ts · GENERATED by tools/site_port/gen_faces.cjs. Do not edit; re-run the tool.
// Every face the approved styles draw, its file under public/site-fonts (content-hashed names, cached for a year),
// and the size-matched fallback computed from the file by next/font/local's own routine.
export type Face = { pkg: string; version: string; category: string; files: { weight: string; style: string; file: string; bytes: number }[];
  fallback: { fallbackFont: string; ascentOverride: string; descentOverride: string; lineGapOverride: string; sizeAdjust: string } };
export const FACES: Record<string, Face> = {
 "Bodoni Moda": {
  "pkg": "bodoni-moda",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/bodoni-moda-latin-400-normal.e2863d3bbe.woff2",
    "bytes": 14528
   },
   {
    "weight": "400",
    "style": "italic",
    "file": "/site-fonts/bodoni-moda-latin-400-italic.783fd966b8.woff2",
    "bytes": 16552
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/bodoni-moda-latin-500-normal.ec5b785abb.woff2",
    "bytes": 15020
   }
  ],
  "fallback": {
   "ascentOverride": "97.77%",
   "descentOverride": "34.76%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "115.07%"
  }
 },
 "Inter Tight": {
  "pkg": "inter-tight",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/inter-tight-latin-400-normal.6f32da94d4.woff2",
    "bytes": 22016
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/inter-tight-latin-500-normal.6c0019f88d.woff2",
    "bytes": 22616
   }
  ],
  "fallback": {
   "ascentOverride": "99.65%",
   "descentOverride": "24.81%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "97.21%"
  }
 },
 "Cormorant Garamond": {
  "pkg": "cormorant-garamond",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "italic",
    "file": "/site-fonts/cormorant-garamond-latin-400-italic.e48e580270.woff2",
    "bytes": 23660
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/cormorant-garamond-latin-500-normal.8197bf5361.woff2",
    "bytes": 23312
   },
   {
    "weight": "500",
    "style": "italic",
    "file": "/site-fonts/cormorant-garamond-latin-500-italic.4fb55a7a6d.woff2",
    "bytes": 23924
   }
  ],
  "fallback": {
   "ascentOverride": "95.81%",
   "descentOverride": "29.76%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "96.44%"
  }
 },
 "Manrope": {
  "pkg": "manrope",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/manrope-latin-400-normal.849290ef12.woff2",
    "bytes": 14108
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/manrope-latin-500-normal.1987431874.woff2",
    "bytes": 14044
   }
  ],
  "fallback": {
   "ascentOverride": "102.74%",
   "descentOverride": "28.91%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "103.76%"
  }
 },
 "Italiana": {
  "pkg": "italiana",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/italiana-latin-400-normal.5079c87a4e.woff2",
    "bytes": 10100
   }
  ],
  "fallback": {
   "ascentOverride": "86.90%",
   "descentOverride": "23.41%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "106.78%"
  }
 },
 "Jost": {
  "pkg": "jost",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "300",
    "style": "normal",
    "file": "/site-fonts/jost-latin-300-normal.4755701d1a.woff2",
    "bytes": 9876
   },
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/jost-latin-400-normal.f94cffda16.woff2",
    "bytes": 9404
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/jost-latin-500-normal.98dce4f076.woff2",
    "bytes": 10476
   }
  ],
  "fallback": {
   "ascentOverride": "115.22%",
   "descentOverride": "40.38%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "92.86%"
  }
 },
 "Marcellus": {
  "pkg": "marcellus",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/marcellus-latin-400-normal.8a539799d1.woff2",
    "bytes": 14552
   }
  ],
  "fallback": {
   "ascentOverride": "87.10%",
   "descentOverride": "25.02%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "111.84%"
  }
 },
 "Mulish": {
  "pkg": "mulish",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/mulish-latin-400-normal.95efc771d1.woff2",
    "bytes": 13364
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/mulish-latin-500-normal.9d6af22335.woff2",
    "bytes": 13272
   },
   {
    "weight": "400",
    "style": "italic",
    "file": "/site-fonts/mulish-latin-400-italic.e1ba733040.woff2",
    "bytes": 14280
   }
  ],
  "fallback": {
   "ascentOverride": "95.71%",
   "descentOverride": "23.81%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "105.00%"
  }
 },
 "Fraunces": {
  "pkg": "fraunces",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "300",
    "style": "normal",
    "file": "/site-fonts/fraunces-latin-300-normal.eb79786009.woff2",
    "bytes": 17928
   },
   {
    "weight": "300",
    "style": "italic",
    "file": "/site-fonts/fraunces-latin-300-italic.74cb64bfa9.woff2",
    "bytes": 22816
   },
   {
    "weight": "400",
    "style": "italic",
    "file": "/site-fonts/fraunces-latin-400-italic.475b154af1.woff2",
    "bytes": 22852
   }
  ],
  "fallback": {
   "ascentOverride": "87.55%",
   "descentOverride": "22.83%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "111.71%"
  }
 },
 "Plus Jakarta Sans": {
  "pkg": "plus-jakarta-sans",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/plus-jakarta-sans-latin-400-normal.221a4135d0.woff2",
    "bytes": 11816
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/plus-jakarta-sans-latin-500-normal.bad081c8db.woff2",
    "bytes": 12312
   }
  ],
  "fallback": {
   "ascentOverride": "98.16%",
   "descentOverride": "20.99%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "105.75%"
  }
 },
 "Instrument Serif": {
  "pkg": "instrument-serif",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/instrument-serif-latin-400-normal.5eb09b5ac0.woff2",
    "bytes": 21032
   },
   {
    "weight": "400",
    "style": "italic",
    "file": "/site-fonts/instrument-serif-latin-400-italic.5a51946dff.woff2",
    "bytes": 22128
   }
  ],
  "fallback": {
   "ascentOverride": "117.87%",
   "descentOverride": "36.91%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "83.99%"
  }
 },
 "Instrument Sans": {
  "pkg": "instrument-sans",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/instrument-sans-latin-400-normal.9a91efaa35.woff2",
    "bytes": 16860
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/instrument-sans-latin-500-normal.9d3547da16.woff2",
    "bytes": 17232
   }
  ],
  "fallback": {
   "ascentOverride": "93.97%",
   "descentOverride": "24.22%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "103.22%"
  }
 },
 "Gilda Display": {
  "pkg": "gilda-display",
  "version": "5.3.0",
  "category": "serif",
  "files": [
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/gilda-display-latin-400-normal.d2b0a9deb0.woff2",
    "bytes": 20204
   }
  ],
  "fallback": {
   "ascentOverride": "80.69%",
   "descentOverride": "25.78%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Times New Roman",
   "sizeAdjust": "110.55%"
  }
 },
 "Figtree": {
  "pkg": "figtree",
  "version": "5.3.0",
  "category": "sans-serif",
  "files": [
   {
    "weight": "300",
    "style": "normal",
    "file": "/site-fonts/figtree-latin-300-normal.3a8ad33722.woff2",
    "bytes": 10696
   },
   {
    "weight": "400",
    "style": "normal",
    "file": "/site-fonts/figtree-latin-400-normal.8f98dd6429.woff2",
    "bytes": 11384
   },
   {
    "weight": "500",
    "style": "normal",
    "file": "/site-fonts/figtree-latin-500-normal.953a6a4294.woff2",
    "bytes": 11432
   }
  ],
  "fallback": {
   "ascentOverride": "95.06%",
   "descentOverride": "25.02%",
   "lineGapOverride": "0.00%",
   "fallbackFont": "Arial",
   "sizeAdjust": "99.94%"
  }
 }
};
