// lib/partner/words.ts · CE-47 · PTN-A1 app · every word a partner, a vendor or the admin reads on these pages, ONE HOME.
// The founder's one rule: simple and descriptive. The ruled lines are verbatim (fee line, "Who is signing up?", "Just me ·",
// "Report", "Calls for you", "Tick "She asked for this" first."). r4: the partner mark is the founder's "Verified" /
// "Unverified" (7 Oct 2026); its words come from the server (check_words), and when it sends null no mark is drawn.
export const FEE_LINE = 'This partner may charge its own fees. TDW takes no fee and has no part in it.';
export const W = {
  brand: 'The Dream Wedding',
  partnerWith: 'Partner with The Dream Wedding',
  whoTitle: 'Who is signing up?',
  whoLede: 'Agencies, fashion houses, brands, wedding planners and studios can get collab calls and post work for wedding vendors. Signing up is free. Your first 3 connections are free. After that, the partner plan costs Rs 2,999 a month.',
  orgChoice: 'An organisation',
  orgChoiceSub: 'An agency, fashion house, brand, wedding planner, studio or other business',
  meChoice: 'Just me',
  meChoiceSub: 'This choice is for a freelance stylist, model or photographer. You will join Collab Hub.',
  whoNext: 'Next, you give your phone number and your name, and TDW sends you a code on WhatsApp. After that, you add your organisation and its Instagram handle.',
  signInLine: 'Are you already a partner?',
  signIn: 'Sign in',
  soonTitle: 'Launching soon',
  soonLine: 'Collab Hub for freelance stylists, models and photographers opens soon.',
  back: 'Back',
  phone: 'Phone number',
  phoneHint: 'Write the number with the country code, for example +91 98111 00021.',
  sendCode: 'Send code on WhatsApp',
  code: 'The 6-digit code from WhatsApp',
  yourName: 'Your name',
  verify: 'Continue',
  newCode: 'Send a new code',
  orgTitle: 'Your organisation',
  orgLede: 'What you write here shows on your partner page.',
  // A tap on the mark: what it means and what it does not (the rule's lines 1 and 2, with the founder for approval; the
  // mark itself shows only once he rules and the switch is on).
  markMeans: 'Verified means TDW has seen that the organisation is real: its own website or Instagram, and a call with a named person there.',
  markNot: 'It does not mean TDW vouches for its work, its fees or its people.',
  pageLink: 'Your partner page',
  pageOpen: 'Open your partner page',
  copy: 'Copy',
  copied: 'Copied',
  orgName: 'Name of your organisation',
  kind: 'What kind of organisation?',
  insta: 'Instagram handle',
  instaHint: 'Write the handle only, for example modelconnect.in.',
  website: 'Website (optional)',
  websiteHint: 'Write the full address, for example https://modelconnect.in.',
  callsEmail: 'Email for calls (optional)',
  cities: 'Cities',
  saveOrg: 'Save and open my partner area',
  callsTab: 'Calls for you',
  briefsTab: 'Your briefs',
  reqTab: 'Your requirements',
  settingsTab: 'Settings',
  callsSoon: 'TDW emails you each collab call that fits your cities and your people. This tab will list your calls soon.',
  briefsSoon: 'Briefs are not open yet. When they open, you will post a brief here and choose who to work with.',
  reqSoon: 'Requirements are not open yet. When they open, you will post paid work here and choose who to work with.',
  footCalls: 'TDW sends calls to your organisation, not to your people. For each person you suggest, TDW keeps only their name, role and profile link. TDW never contacts them.',
  people: 'People',
  addPerson: 'Add someone',
  addPersonLine: 'Each person signs in with their own phone number and a code sent on WhatsApp. TDW sends them nothing until they sign in.',
  ownerOnly: 'Only the owner of this partner account can add people.',
  receive: 'Calls',
  getCalls: 'Get calls',
  stopCalls: 'Stop calls for a while',
  signOut: 'Sign out',
  saved: 'Your changes are saved.',
  tryAgain: 'TDW could not finish this just now. Please try again.',
  publicLede: (name: string) => `${name} is a partner on The Dream Wedding.`,
  workedWith: 'Worked with',
  report: 'Report',
  reqFromTdw: 'The Dream Wedding sent you this request.',
  reqAnswer: 'To answer this request, sign up first. TDW then shows your answer to the vendor.',
  reqOrg: 'Answer for an organisation',
  reqOrgSub: 'This choice is for an agency, fashion house, brand, wedding planner or studio. Signing up is free. Your first 3 connections are free.',
  reqMe: 'Answer just for me',
  reqMeSub: 'This choice is for a freelance stylist, model or photographer. You will join Collab Hub, which is free.',
  reqEnded: 'This request is closed, because its date has passed.',
  notFound: 'This page does not exist.',
} as const;

// PTN-A2-1 app part 1 · THE CALL PAGE (/partner/call/<token>), the page a partner opens from a call's email or WhatsApp
// message. R-47.1 (the founder's rule, 8 Oct 2026): every line is a complete sentence with one idea, and says who does what.
export const CALL = {
  eyebrow: 'A collab call sent to you by The Dream Wedding',
  needs: (vendor: string, needs: string) => `${vendor} needs ${needs}.`,
  trade: (vendor: string, trade: string) => `${vendor} is a ${trade} on The Dream Wedding.`,
  where: (city: string, date: string) => `The shoot is in ${city} on ${date}.`,
  pay: (pay: string) => `The vendor offers this pay: ${pay}.`,
  note: 'The vendor wrote this note:',
  insta: "You can see the vendor's Instagram here:",
  closed: 'This call is no longer open, because the vendor closed it or its date has passed.',
  already: 'You have already suggested these people for this call:',
  formTitle: 'Suggest someone',
  formLede: (max: number) => `You can suggest up to ${max} people. For each person, write their name and, if you have one, a link to their profile.`,
  name: 'Name',
  role: 'Role',
  link: 'Profile link (optional)',
  linkHint: 'You can paste a link to their Instagram profile or their website.',
  addRow: 'Add another person',
  removeRow: 'Remove',
  agree: 'These people have agreed to be suggested for this call',
  send: 'Send suggestions',
  sending: 'Sending',
  how: (partner: string) => `If the vendor chooses someone, the vendor contacts ${partner}, not the person.`,
  keeps: "TDW keeps only each person's name, role and profile link. TDW never contacts the people you suggest.",
  fewerTitle: 'Getting too many calls?',
  fewerLede: 'You can pause calls for one week, or stop them. To get calls again later, sign in and turn them on in Settings.',
  pause: 'Pause calls for one week',
  stop: 'Stop all calls',
  confirmPause: 'You opened the link to pause calls. Press the button below to pause them for one week.',
  confirmStop: 'You opened the link to stop calls. Press the button below to stop them.',
  noCall: 'This link does not work. Ask The Dream Wedding for a new one.',
} as const;

export const KINDS: { key: string; label: string }[] = [
  { key: 'talent_agency', label: 'Talent agency' }, { key: 'model_agency', label: 'Model agency' },
  { key: 'fashion_house', label: 'Fashion house' }, { key: 'studio', label: 'Studio' }, { key: 'brand', label: 'Brand' },
  { key: 'wedding_planner', label: 'Wedding planner' }, { key: 'other', label: 'Other' },
];
export const CONTACT_KINDS: { key: string; label: string }[] = [
  { key: 'agency', label: 'Agency' }, { key: 'fashion_house', label: 'Fashion house' }, { key: 'brand', label: 'Brand' },
  { key: 'studio', label: 'Studio' }, { key: 'planner', label: 'Planner' }, { key: 'stylist', label: 'Stylist' },
  { key: 'model', label: 'Model' }, { key: 'influencer', label: 'Influencer' }, { key: 'other', label: 'Other' },
];
