// lib/partner/words.ts · CE-47 · PTN-A1 app · every word a partner, a vendor or the admin reads on these pages, ONE HOME.
// The founder's one rule: simple and descriptive. The ruled lines are verbatim (fee line, "Who is signing up?", "Just me ·",
// "Report", "Calls for you", "Tick "She asked for this" first."). r4: the partner mark is the founder's "Verified" /
// "Unverified" (7 Oct 2026); its words come from the server (check_words), and when it sends null no mark is drawn.
export const FEE_LINE = 'This partner may charge its own fees. TDW takes no fee and has no part in it.';
export const W = {
  brand: 'The Dream Wedding',
  partnerWith: 'Partner with The Dream Wedding',
  whoTitle: 'Who is signing up?',
  whoLede: 'Agencies, fashion houses, brands, wedding planners and studios can get collab calls and post work for wedding vendors. Signing up is free. Your first 3 connections are free. After that it is Rs 2,999 a month.',
  orgChoice: 'An organisation',
  orgChoiceSub: 'An agency, fashion house, brand, wedding planner, studio or other business',
  meChoice: 'Just me',
  meChoiceSub: 'For a freelance stylist, model or photographer. You will join Collab Hub.',
  whoNext: 'Next: your phone number, your name and a code sent on WhatsApp. Then your organisation and its Instagram handle.',
  signInLine: 'Already a partner?',
  signIn: 'Sign in',
  soonTitle: 'Launching soon',
  soonLine: 'Collab Hub for freelance stylists, models and photographers opens soon.',
  back: 'Back',
  phone: 'Phone number',
  phoneHint: 'With the country code, for example +91 98111 00021',
  sendCode: 'Send code on WhatsApp',
  code: 'The 6-digit code from WhatsApp',
  yourName: 'Your name',
  verify: 'Continue',
  newCode: 'Send a new code',
  orgTitle: 'Your organisation',
  orgLede: 'This shows on your partner page.',
  // A tap on the mark: what it means and what it does not (the rule's lines 1 and 2, with the founder for approval; the
  // mark itself shows only once he rules and the switch is on).
  markMeans: 'Verified means TDW has seen that the organisation is real: its own website or Instagram, and a call with a named person there.',
  markNot: 'It does not mean TDW vouches for its work, its fees or its people.',
  pageLink: 'Your partner page',
  pageOpen: 'Open your partner page',
  copy: 'Copy',
  copied: 'Copied',
  orgName: 'Name of your organisation',
  kind: 'What kind of organisation?',
  insta: 'Instagram handle',
  instaHint: 'The handle only, for example modelconnect.in',
  website: 'Website (optional)',
  websiteHint: 'For example https://modelconnect.in',
  callsEmail: 'Email for calls (optional)',
  cities: 'Cities',
  saveOrg: 'Save and open my partner area',
  callsTab: 'Calls for you',
  briefsTab: 'Your briefs',
  reqTab: 'Your requirements',
  settingsTab: 'Settings',
  callsSoon: 'Calls start soon. When a vendor posts a collab call that fits your cities and people, it shows here and in your email.',
  briefsSoon: 'Briefs start soon. You will post a brief here, see who applies and pick who to work with.',
  reqSoon: 'Requirements start soon. You will post paid work here, see who applies and pick who to work with.',
  footCalls: 'Calls come to you, not to your people. For each person you suggest, TDW keeps only their name, role and profile link. TDW never contacts them.',
  people: 'People',
  addPerson: 'Add someone',
  addPersonLine: 'They sign in with their own phone and a WhatsApp code. TDW sends them nothing until they sign in.',
  ownerOnly: 'Only the owner can add people.',
  receive: 'Calls',
  getCalls: 'Get calls',
  stopCalls: 'Stop calls for a while',
  signOut: 'Sign out',
  saved: 'Saved.',
  tryAgain: 'Something went wrong. Please try again.',
  publicLede: (name: string) => `${name} is a partner on The Dream Wedding.`,
  workedWith: 'Worked with',
  report: 'Report',
  reqFromTdw: 'A request sent to you by The Dream Wedding',
  reqAnswer: 'To answer, sign up. Your answer goes to the vendor inside The Dream Wedding.',
  reqOrg: 'Answer for an organisation',
  reqOrgSub: 'An agency, fashion house, brand, wedding planner or studio. Signing up is free. Your first 3 connections are free.',
  reqMe: 'Answer just for me',
  reqMeSub: 'For a freelance stylist, model or photographer. You will join Collab Hub. It is free.',
  reqEnded: 'This request has ended. Its date has passed.',
  notFound: 'This page does not exist.',
} as const;

export const KINDS: { key: string; label: string }[] = [
  { key: 'talent_agency', label: 'Talent agency' }, { key: 'model_agency', label: 'Model agency' },
  { key: 'fashion_house', label: 'Fashion house' }, { key: 'studio', label: 'Studio' }, { key: 'brand', label: 'Brand' },
  { key: 'wedding_planner', label: 'Wedding planner' }, { key: 'other', label: 'Other' },
];
export const CONTACT_KINDS: { key: string; label: string }[] = [
  { key: 'agency', label: 'Agency' }, { key: 'fashion_house', label: 'Fashion house' }, { key: 'brand', label: 'Brand' },
  { key: 'studio', label: 'Studio' }, { key: 'planner', label: 'Planner' }, { key: 'stylist', label: 'Stylist' },
  { key: 'model', label: 'Model' }, { key: 'influencer', label: 'Influencer' }, { key: 'other', label: 'Other' },
];
