// lib/site/styles/aurora.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/aurora.html sha256 b6bdc11b26e2fa2cbababf1d709ddf41e2d182828455644d5cdc994607aa1d1d (WEB-3's approved rendition, verbatim).
export const CSS = `
:root{--bg:#fbf3f1;--ink:#2b1f2e;--mute:#7c6a78;--line:rgba(43,31,46,.12);--soft:rgba(255,255,255,.5);--accent:#c2527a;--on-accent:#fff;
 --b1:#f7b8c9;--b2:#ffd2b0;--b3:#d6c4f7;--b4:#bfe3f2;--glass:rgba(255,255,255,.38);--gline:rgba(255,255,255,.7);
 --grad:linear-gradient(110deg,#c2527a,#d86c44 35%,#8f6ad6 70%,#c2527a);--serif:"Fraunces",Georgia,serif;--sans:"Plus Jakarta Sans","Helvetica Neue",sans-serif;--r:26px;--br:999px}
html[data-pal=lagoon]{--bg:#f0f7f5;--ink:#15302d;--mute:#5b736f;--accent:#2e8f86;--b1:#a8e6d2;--b2:#c3d6ff;--b3:#e3cbf7;--b4:#fff0b8;--grad:linear-gradient(110deg,#2e8f86,#5b7fd6 40%,#a36ad0 75%,#2e8f86)}
html[data-pal=dusk]{--bg:#16121f;--ink:#f3ecf6;--mute:#b0a2bb;--line:rgba(255,255,255,.14);--soft:rgba(255,255,255,.08);--accent:#f0a07c;--on-accent:#1a1422;--b1:#6d3f86;--b2:#c9665a;--b3:#34479a;--b4:#b0467e;--glass:rgba(40,28,54,.42);--gline:rgba(255,255,255,.16);--grad:linear-gradient(110deg,#f0a07c,#f3c3e0 40%,#a9a6ff 75%,#f0a07c)}
html[data-font=b]{--serif:"Instrument Serif",Georgia,serif}
html{background:var(--bg)}body{background:transparent}
.wash{position:fixed;inset:-20vmax;z-index:-1;pointer-events:none;filter:blur(60px) saturate(1.15);opacity:.95}
.wash i{position:absolute;width:62vmax;height:62vmax;border-radius:50%;mix-blend-mode:normal;animation:float1 calc(28s / var(--k)) ease-in-out infinite alternate}
.wash i:nth-child(1){background:radial-gradient(circle,var(--b1),transparent 64%);left:-6%;top:0}
.wash i:nth-child(2){background:radial-gradient(circle,var(--b2),transparent 64%);right:-10%;top:18%;animation-name:float2;animation-duration:calc(34s / var(--k))}
.wash i:nth-child(3){background:radial-gradient(circle,var(--b3),transparent 64%);left:20%;bottom:-8%;animation-name:float3;animation-duration:calc(40s / var(--k))}
.wash i:nth-child(4){background:radial-gradient(circle,var(--b4),transparent 64%);right:12%;bottom:18%;animation-name:float1;animation-duration:calc(46s / var(--k));animation-delay:-12s}
@keyframes float1{to{transform:translate(18vmax,14vmax) scale(1.15)}}@keyframes float2{to{transform:translate(-22vmax,10vmax) scale(.9)}}@keyframes float3{to{transform:translate(8vmax,-20vmax) scale(1.2)}}
.glass{background:var(--glass);backdrop-filter:blur(22px) saturate(1.6);-webkit-backdrop-filter:blur(22px) saturate(1.6);border:1px solid var(--gline);box-shadow:0 10px 40px -20px rgba(60,20,60,.35)}
.gtx{background:var(--grad);background-size:250% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:gmove calc(12s / var(--k)) linear infinite}
@keyframes gmove{to{background-position:-250% 0}}
.pill{display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;font:500 11.5px/1 var(--sans);letter-spacing:.04em}
/* header: floating glass */
.hd{position:fixed;z-index:30;left:10px;right:10px;top:calc(10px + env(safe-area-inset-top,0px));height:54px;border-radius:999px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 8px 0 10px;transition:transform .6s var(--ease)}
.hd .l{justify-self:start;display:flex;gap:2px;align-items:center}.hd .r{justify-self:end;display:flex;gap:6px;align-items:center}
.wmt{font:italic 400 19px/1 var(--serif);white-space:nowrap;letter-spacing:.01em}
.hd .mono{display:none}.hd.use-mono .wmt{display:none}.hd.use-mono .mono{display:inline-flex}
.enq{background:var(--ink);color:var(--bg);border-radius:999px;padding:0 16px;height:38px;font:500 12px/1 var(--sans)}
.hd .r .heart{display:none}.ml{display:none;font:500 12px var(--sans)}
/* cover */
.cover{position:relative;min-height:100svh;padding:calc(92px + env(safe-area-inset-top,0px)) var(--pad) 40px;overflow:hidden}
.cover .pill{opacity:0;transform:translateY(10px);transition:opacity .9s var(--ease) .2s,transform .9s var(--ease) .2s}.cover.go .pill{opacity:1;transform:none}
.h1{font:300 clamp(48px,15vw,150px)/.95 var(--serif);letter-spacing:-.03em;margin:16px 0 0;position:relative;z-index:2}
.h1 em{font-style:italic}
.h1 .ln>span{transition-duration:calc(1.3s * var(--k))}
.floats{position:relative;height:clamp(380px,112vw,720px);margin-top:18px}
.fl{position:absolute;border-radius:var(--r);overflow:hidden;will-change:transform;box-shadow:0 30px 60px -30px rgba(60,20,60,.5);border:1px solid var(--gline)}
.fl img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
.fl.a{left:14%;right:0;top:5%;bottom:5%}.fl.b{left:0;bottom:0;width:40%;aspect-ratio:3/4;z-index:2}.fl.c{right:5%;top:0;width:30%;aspect-ratio:4/5;z-index:2}
.fl .inner{position:absolute;inset:0;animation:bob calc(7s / var(--k)) ease-in-out infinite alternate}
.fl.b .inner{animation-duration:calc(8.5s / var(--k));animation-delay:-2s}.fl.c .inner{animation-duration:calc(6s / var(--k));animation-delay:-4s}
@keyframes bob{to{transform:translateY(-10px)}}
.fl{opacity:0;transform:translateY(40px) scale(.94);transition:opacity 1.3s var(--ease),transform 1.6s var(--ease)}.cover.go .fl{opacity:1;transform:none}
.cover.go .fl.b{transition-delay:.25s}.cover.go .fl.c{transition-delay:.45s}
.cta{display:flex;gap:10px;align-items:center;margin-top:22px;position:relative;z-index:3;flex-wrap:wrap}
.glow{position:relative;border-radius:999px;padding:0 24px;min-height:52px;display:inline-flex;align-items:center;gap:10px;font:500 13.5px/1 var(--sans);color:var(--ink);isolation:isolate}
.glow::before{content:"";position:absolute;inset:-1.5px;border-radius:inherit;z-index:-2;background:conic-gradient(from var(--a,0deg),var(--b1),var(--accent),var(--b3),var(--b2),var(--b1));animation:spin calc(5s / var(--k)) linear infinite}
.glow::after{content:"";position:absolute;inset:1px;border-radius:inherit;z-index:-1;background:var(--bg)}
@property --a{syntax:'<angle>';inherits:false;initial-value:0deg}
@keyframes spin{to{--a:360deg}}
.chipsline{display:flex;gap:8px;flex-wrap:wrap}
/* pinned story */
.pin{position:relative;height:300vh}
.pin .stage{position:sticky;top:0;height:100svh;overflow:hidden;display:flex;flex-direction:column;justify-content:center;padding:84px var(--pad) 30px;gap:18px}
.pin .say{font-size:clamp(22px,min(8.6vw,4.6vh),72px)!important}
.pin .imgs{position:relative;flex:1;max-height:56vh;border-radius:var(--r);overflow:hidden}
.pin .imgs .ph{position:absolute;inset:0;opacity:0;transition:opacity .9s ease,transform 1.2s var(--ease);transform:scale(1.06)}.pin .imgs .ph.on{opacity:1;transform:none}
.pin .say{font:300 clamp(30px,8.6vw,72px)/1.08 var(--serif);letter-spacing:-.02em}
.pin .say span{opacity:.16;transition:opacity .35s linear}.pin .say span.lit{opacity:1}
.pin .step{display:flex;gap:6px}.pin .step i{height:3px;flex:1;border-radius:3px;background:var(--line);overflow:hidden;position:relative}.pin .step i b{position:absolute;inset:0;background:var(--ink);transform-origin:left;transform:scaleX(var(--p,0))}
/* sections */
section{padding:clamp(52px,12vw,120px) 0 0}
.sh{padding:0 var(--pad);margin-bottom:26px}
.sh h2{font:300 clamp(34px,10vw,84px)/1 var(--serif);letter-spacing:-.025em;margin:12px 0 0}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:0 var(--pad)}
.card{display:block;position:relative;border-radius:var(--r);overflow:hidden;aspect-ratio:3/4.3;transform:translateY(0);animation:bob calc(8s / var(--k)) ease-in-out infinite alternate;animation-delay:calc(var(--i) * -1.3s)}
.card.rv{opacity:0;transform:scale(.92);filter:blur(8px);transition:opacity 1s var(--ease),transform 1.1s var(--ease),filter 1s var(--ease)}.card.rv.in{opacity:1;transform:none;filter:none}
.card .ph{position:absolute;inset:0}.card .ph img{transition:transform 1.4s var(--ease)}.card:hover .ph img{transform:scale(1.05)}
.card .cap{position:absolute;z-index:2;left:8px;right:8px;bottom:8px;border-radius:18px;padding:10px 12px}
.card .cap.glass{background:color-mix(in srgb,var(--bg) 80%,transparent)}
.card .hbtn.glass{background:color-mix(in srgb,var(--bg) 70%,transparent)}
.card .nm{font:400 16px/1.2 var(--serif)}.card .pr{font:400 11.5px/1.2 var(--sans);color:var(--mute);margin-top:3px}
.card .hbtn{position:absolute;z-index:2;right:8px;top:8px;border-radius:50%;width:38px;height:38px}
.card .vidtag{position:absolute;z-index:2;left:8px;top:8px;align-items:center;gap:6px;border-radius:999px;padding:6px 10px;font:500 11px/1 var(--sans)}
.card .vidtag svg{width:10px;height:10px;fill:currentColor}
.rail{display:flex;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:0 var(--pad) 10px;scroll-padding:0 var(--pad)}.rail::-webkit-scrollbar{display:none}
.coll{flex:none;width:72vw;max-width:340px;scroll-snap-align:start;border-radius:var(--r);padding:8px}
.coll .ph{aspect-ratio:4/4.6;border-radius:calc(var(--r) - 8px)}.coll .cap{display:flex;justify-content:space-between;align-items:center;padding:12px 8px 6px}
.coll b{font:400 19px/1.2 var(--serif);font-weight:400}.coll span{color:var(--mute);font-size:12px}
.revp{margin:0 var(--pad);border-radius:calc(var(--r) + 6px);padding:30px 22px 22px}
.q p{font:300 clamp(24px,6.8vw,44px)/1.22 var(--serif);letter-spacing:-.01em;margin:0 0 18px}
.q .by{font:500 12px var(--sans);color:var(--mute)}
.qnav{display:flex;gap:8px;align-items:center;margin-top:20px}.qnav button{width:44px;height:44px;border-radius:50%;background:var(--glass);border:1px solid var(--gline);display:flex;align-items:center;justify-content:center}
.qnav svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.5}.qnav span{margin-left:6px;font:500 12px var(--sans);color:var(--mute)}
.price{padding:0 var(--pad);display:flex;flex-direction:column;gap:8px}
.row{display:flex;justify-content:space-between;align-items:center;gap:12px;border-radius:20px;padding:16px 18px}
.row .n{font:400 17px/1.3 var(--serif)}.row .v{font:500 12.5px/1 var(--sans);white-space:nowrap;padding:8px 12px;border-radius:999px;background:var(--ink);color:var(--bg)}
.note{color:var(--mute);font-size:13px;margin:10px 0 0}
.story{padding:0 var(--pad);display:grid;gap:22px}.story .ph{aspect-ratio:4/4.6;border-radius:var(--r)}
.story .lead{font:300 clamp(26px,7.4vw,48px)/1.12 var(--serif);letter-spacing:-.015em;margin:10px 0 14px}.story p{color:var(--mute);margin:0;max-width:44ch}
.faq{padding:0 var(--pad);display:flex;flex-direction:column;gap:8px}.fq{border:1px solid var(--gline);background:var(--glass);border-radius:20px;padding:0 18px;backdrop-filter:blur(18px)}
.fq button{font:400 18px/1.3 var(--serif)}
footer{margin-top:clamp(64px,13vw,130px);padding:0 var(--pad) calc(96px + env(safe-area-inset-bottom,0px))}
.askp{border-radius:calc(var(--r) + 8px);padding:30px 22px;display:flex;flex-direction:column;gap:16px;align-items:flex-start}
.askp .t{font:300 clamp(30px,8.4vw,60px)/1.05 var(--serif);letter-spacing:-.02em}
.fname{font:300 60px/1 var(--serif);font-style:italic;letter-spacing:-.03em;margin:48px 0 20px;white-space:nowrap}
.flinks{display:flex;flex-wrap:wrap;gap:8px}.credit{margin-top:22px;color:var(--mute);font-size:12px}
/* chrome dress */
.drawer{background:var(--glass);backdrop-filter:blur(26px) saturate(1.5);-webkit-backdrop-filter:blur(26px) saturate(1.5);border-radius:0 28px 28px 0;border-right:1px solid var(--gline)}
#dnav a{font:300 34px/1.2 var(--serif);letter-spacing:-.02em}
.ez{background:var(--glass);backdrop-filter:blur(26px) saturate(1.5);-webkit-backdrop-filter:blur(26px) saturate(1.5);border-top:1px solid var(--gline)}
.ez .eh{border-color:var(--line)}.emono{border-color:var(--accent);color:var(--accent)}.m.u{background:var(--ink);color:var(--bg)}
.btn{text-transform:none;letter-spacing:.01em;font:500 13.5px/1 var(--sans)}
.btn-main{background:var(--ink);color:var(--bg)}.btn-alt{border:1px solid var(--line);background:var(--glass)}
.chip{text-transform:none;letter-spacing:0;font:500 12.5px/1 var(--sans);border-color:var(--line);background:var(--glass)}
.lp{background:var(--bg)}.lp .gal .ph{border-radius:0}.lpt{font-weight:300;letter-spacing:-.02em}.crumb{text-transform:none;letter-spacing:0;font:500 12px var(--sans)}
.scrim{background:rgba(40,20,40,.25);backdrop-filter:blur(4px)}
@media (min-width:700px){.ml{display:inline}.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}.hd{left:50%;right:auto;width:min(860px,94vw);transform:translateX(-50%)}}
@media (min-width:1024px){
 .cover{display:grid;grid-template-columns:1.05fr 1fr;grid-template-areas:'t f' 'c f';align-items:center;gap:0 3vw;padding-top:110px}.cover>div:first-child{grid-area:t;align-self:end}.cover .floats{grid-area:f}.cover .cta{grid-area:c;align-self:start}.floats{height:74vh;margin-top:0}
 .pin .stage{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:5vw;padding:100px 6vw 40px}.pin .imgs{height:70vh;max-height:none}
 .pin .say{font-size:clamp(24px,min(3.6vw,5.6vh),60px)}
 .grid{grid-template-columns:repeat(4,1fr);gap:18px;max-width:1300px;margin:0 auto}.coll{width:26vw}
 .story{grid-template-columns:1fr 1fr;align-items:center;max-width:1200px;margin:0 auto}.revp,.price,.faq{max-width:900px;margin-left:auto;margin-right:auto}
}
@media (prefers-reduced-motion:reduce){.wash i,.card,.fl .inner{animation:none!important}.fl,.cover .pill{opacity:1!important;transform:none!important}.card.rv{opacity:1!important;filter:none!important;transform:none!important}.pin{height:auto}.pin .stage{position:relative;height:auto}.pin .say span{opacity:1}}
`;
