// lib/site/styles/couture.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/couture.html sha256 df3c360f14b876eff6a5916b12506effc241d1f812187365e666d433c6883c0d (WEB-3's approved rendition, verbatim).
export const CSS = `
:root{
  --bg:#ffffff;--ink:#0b0b0b;--mute:#6b6b6b;--line:rgba(11,11,11,.12);--soft:#f4f2ef;
  --tick-bg:#efedea;--tick-ink:#0b0b0b;--accent:#0b0b0b;--on-accent:#ffffff;
  --serif:"Bodoni Moda",Didot,"Bodoni 72",Georgia,serif;--sans:"Inter Tight","Helvetica Neue",Arial,sans-serif;
  --ease:cubic-bezier(.22,.8,.2,1);--wipe:cubic-bezier(.77,0,.18,1);--k:1;
  --pad:clamp(16px,4.4vw,40px);
  box-sizing:border-box;padding-bottom:env(safe-area-inset-bottom,0px);
}
html[data-pal=emerald]{--bg:#f7f5f0;--ink:#10231c;--mute:#5a6b63;--line:rgba(16,35,28,.14);--soft:#ecebe3;--tick-bg:#1f4d3a;--tick-ink:#f7f5f0;--accent:#1f4d3a;--on-accent:#f7f5f0}
html[data-pal=rose]{--bg:#fbf6f4;--ink:#2a1618;--mute:#7d6164;--line:rgba(42,22,24,.13);--soft:#f3e7e3;--tick-bg:#f1e1dc;--tick-ink:#2a1618;--accent:#7e2f3b;--on-accent:#fbf6f4}
html[data-font=b]{--serif:"Cormorant Garamond",Garamond,Georgia,serif;--sans:"Manrope","Helvetica Neue",Arial,sans-serif}
html[data-font=c]{--serif:"Instrument Serif",Georgia,serif;--sans:"Instrument Sans","Helvetica Neue",Arial,sans-serif}
html.m-calm{--k:.7}html.m-cinema{--k:1.45}
*,*::before,*::after{box-sizing:inherit}
html,body{margin:0;background:var(--bg);color:var(--ink)}
body{font:400 15px/1.55 var(--sans);-webkit-font-smoothing:antialiased;overflow-x:hidden;transition:background .6s,color .6s}
a{color:inherit;text-decoration:none}button{font:inherit;color:inherit;background:none;border:0;padding:0;cursor:pointer}
img{display:block;max-width:100%}
.caps{font:500 11px/1.3 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.serif{font-family:var(--serif)}

/* ticker */
.ticker{position:relative;z-index:31;height:30px;background:var(--tick-bg);color:var(--tick-ink);overflow:hidden;display:flex;align-items:center;transition:background .6s,color .6s}
.tk-track{display:flex;white-space:nowrap;animation:tick calc(38s / var(--k)) linear infinite;will-change:transform}
.tk-track span{padding:0 28px;font:500 10.5px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase}
.tk-track span::after{content:"";display:inline-block;width:3px;height:3px;border-radius:50%;background:currentColor;opacity:.5;margin-left:56px;vertical-align:middle}
@keyframes tick{to{transform:translateX(-50%)}}

/* header */
.hd{position:fixed;left:0;right:0;top:30px;z-index:30;height:56px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 var(--pad);color:#fff;transition:background .5s var(--ease),color .5s var(--ease),top .4s var(--ease),box-shadow .5s}
.hd.solid{background:color-mix(in srgb,var(--bg) 94%,transparent);color:var(--ink);backdrop-filter:saturate(1.4) blur(14px);-webkit-backdrop-filter:saturate(1.4) blur(14px);box-shadow:0 .5px 0 var(--line);top:0}
.hd .l{justify-self:start;display:flex;gap:18px;align-items:center}.hd .r{justify-self:end;display:flex;gap:16px;align-items:center;justify-content:flex-end}
.ib{display:inline-flex;align-items:center;gap:8px;min-height:44px}
.ib svg{width:20px;height:20px;stroke:currentColor;fill:none;stroke-width:1.4}
.menu-lbl{font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.wm{font:500 17px/1 var(--serif);letter-spacing:.2em;text-transform:uppercase;white-space:nowrap;text-align:center;padding-left:.2em;transition:font-size .4s var(--ease)}
.wm .mono{display:none}
.hd .r .heart{display:none}
@media (min-width:700px){.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}}
.menu-lbl{display:none}@media (min-width:700px){.menu-lbl{display:inline}}
.hd.use-mono .wm .full{display:none}.hd.use-mono .wm .mono{display:inline-flex}
.mono{display:inline-flex;width:34px;height:34px;border:1px solid currentColor;border-radius:50%;align-items:center;justify-content:center;font:500 13px/1 var(--serif);letter-spacing:.06em;padding-left:.06em}
.heart{position:relative}
.heart .n{position:absolute;top:6px;right:-8px;min-width:16px;height:16px;border-radius:8px;background:currentColor;font:600 9px/16px var(--sans);text-align:center;transform:scale(0);transition:transform .45s cubic-bezier(.3,1.6,.4,1)}
.heart .n b{color:var(--bg);font-weight:600}.hd:not(.solid) .heart .n b{color:#111}
.heart.has .n{transform:scale(1)}.heart.bump svg{animation:bump .5s cubic-bezier(.3,1.6,.4,1)}
@keyframes bump{40%{transform:scale(1.35)}}
.enq{font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase;border-bottom:1px solid currentColor;padding-bottom:3px}

/* cover */
.cover{position:relative;height:calc(100svh - 30px);min-height:560px;max-height:1100px;overflow:hidden;background:#141110;color:#fff;touch-action:pan-y}
.slide{position:absolute;inset:0;clip-path:inset(100% 0 0 0);z-index:1}
.slide.on{clip-path:inset(0 0 0 0);z-index:2}
.slide.enter{z-index:3;animation:wipe calc(1.25s * var(--k)) var(--wipe) both}
.slide.leave{z-index:2}
.slide.leave img{transform:scale(1.02) translateY(-4%);transition:transform calc(1.25s * var(--k)) var(--wipe)}
@keyframes wipe{from{clip-path:inset(100% 0 0 0)}to{clip-path:inset(0 0 0 0)}}
.slide img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transform:scale(1.16);transition:transform calc(1.6s * var(--k)) var(--ease)}
.slide.on img,.slide.enter img{transform:scale(1.03)}
.slide.drift img{animation:drift 14s ease-in-out both}
@keyframes drift{from{transform:scale(1.03)}to{transform:scale(1.1) translate3d(-1.2%,-1%,0)}}
.cover::after{content:"";position:absolute;inset:0;z-index:4;pointer-events:none;background:linear-gradient(to bottom,rgba(0,0,0,.42),rgba(0,0,0,0) 26%,rgba(0,0,0,0) 48%,rgba(0,0,0,.62))}
.cats{position:absolute;z-index:6;left:0;right:0;top:56px;display:flex;gap:22px;overflow-x:auto;scrollbar-width:none;padding:10px var(--pad) 12px;border-top:.5px solid rgba(255,255,255,.28)}
.cats::-webkit-scrollbar{display:none}
.cats a{flex:none;position:relative;padding:6px 0;opacity:.78;transition:opacity .3s}
.cats a.on{opacity:1}
.cats .bar{position:absolute;bottom:10px;height:1px;background:#fff;transition:left .5s var(--ease),width .5s var(--ease)}
.segs{position:absolute;z-index:6;left:var(--pad);right:var(--pad);top:114px;display:flex;gap:6px}
.segs button{flex:1;height:18px;display:flex;align-items:center}
.segs i{display:block;height:1.5px;width:100%;background:rgba(255,255,255,.35);position:relative;overflow:hidden}
.segs i::after{content:"";position:absolute;inset:0;background:#fff;transform:scaleX(0);transform-origin:left}
.segs .done i::after{transform:scaleX(1)}
.segs .run i::after{animation:fill var(--dwell,6.5s) linear both}
@keyframes fill{to{transform:scaleX(1)}}
.copy{position:absolute;z-index:6;left:var(--pad);right:calc(var(--pad) + 30px);bottom:calc(34px + env(safe-area-inset-bottom,0px))}
.copy .who{margin-bottom:14px;display:none}
.hd.use-mono ~ main .copy .who{display:block}
.kick{display:block;overflow:hidden}
.h1{font:400 clamp(38px,11.2vw,84px)/.98 var(--serif);letter-spacing:-.015em;margin:10px 0 22px;max-width:14ch}
html[data-font=b] .h1{font-weight:500;font-size:clamp(42px,12.4vw,92px)}
.ln{display:block;overflow:hidden;padding-bottom:.06em}
.ln>span{display:inline-block;transform:translateY(105%);transition:transform calc(1s * var(--k)) var(--ease)}
.copy.in .ln>span{transform:none}
.copy .kick>span{display:inline-block;transform:translateY(110%);transition:transform calc(.8s * var(--k)) var(--ease)}
.copy.in .kick>span{transform:none}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:12px;min-height:50px;padding:0 28px;font:500 11.5px/1 var(--sans);letter-spacing:.16em;text-transform:uppercase;position:relative;overflow:hidden;isolation:isolate}
.btn-w{background:#fff;color:#0b0b0b}
.btn-w::before,.btn-k::before{content:"";position:absolute;inset:0;z-index:-1;transform:translateY(101%);transition:transform .55s var(--ease)}
.btn-w::before{background:var(--accent)}
.btn-w:hover,.btn-w:focus-visible{color:var(--on-accent)}.btn-w:hover::before,.btn-w:focus-visible::before{transform:none}
.btn .ar{transition:transform .45s var(--ease)}.btn:hover .ar{transform:translateX(5px)}
.copy .btn{opacity:0;transform:translateY(14px);transition:opacity .8s var(--ease) .45s,transform .8s var(--ease) .45s,color .55s}
.copy.in .btn{opacity:1;transform:none}
.play{display:none;width:58px;height:58px;border-radius:50%;border:1px solid rgba(255,255,255,.8);align-items:center;justify-content:center;margin-bottom:18px;backdrop-filter:blur(6px)}
.play svg{width:18px;height:18px;fill:#fff;margin-left:3px}
html[data-trade=performer] .cover .play{display:inline-flex;animation:pulse 2.4s var(--ease) infinite}
@keyframes pulse{0%{box-shadow:0 0 0 0 rgba(255,255,255,.35)}70%{box-shadow:0 0 0 18px rgba(255,255,255,0)}}
.cue{position:absolute;z-index:6;right:var(--pad);bottom:calc(40px + env(safe-area-inset-bottom,0px));writing-mode:vertical-rl;font:500 10px/1 var(--sans);letter-spacing:.2em;text-transform:uppercase;opacity:.8}
.cue::after{content:"";display:block;width:1px;height:40px;margin:10px auto 0;background:linear-gradient(#fff,transparent);animation:cue 2s var(--ease) infinite}
@keyframes cue{0%{transform:scaleY(0);transform-origin:top}50%{transform:scaleY(1);transform-origin:top}51%{transform-origin:bottom}100%{transform:scaleY(0);transform-origin:bottom}}

/* sections */
section{padding:clamp(44px,9.5vw,100px) 0 0}
.shead{padding:0 var(--pad);display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:26px}
.shead .caps{display:block}
.shead h2{font:400 clamp(30px,8.4vw,56px)/1.14 var(--serif);letter-spacing:-.01em;margin:.3em 0 0;max-width:15ch}
html[data-font=b] .shead h2{font-weight:500}
.shead .more{flex:none;white-space:nowrap;border-bottom:1px solid currentColor;padding-bottom:3px}
.rv{opacity:0;transform:translateY(calc(26px * var(--k)));transition:opacity calc(.9s * var(--k)) var(--ease),transform calc(.9s * var(--k)) var(--ease);transition-delay:var(--d,0s)}
.rv.in{opacity:1;transform:none}

.grid{display:grid;grid-template-columns:1fr 1fr;gap:28px 10px;padding:0 var(--pad)}
.card{position:relative;display:block}
.ph{position:relative;overflow:hidden;aspect-ratio:3/4;background:var(--soft)}
.ph::before{content:"";position:absolute;inset:-10%;background:var(--lq) center/cover;filter:blur(14px);opacity:.9}
.ph img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
.card .ph img{transition:opacity .7s var(--ease),transform 1.3s var(--ease)}
.card .ph img.b{opacity:0}
.card .ph .mask{position:absolute;inset:0;background:var(--bg);transform-origin:top;transition:transform calc(1.05s * var(--k)) var(--wipe);transition-delay:var(--d,0s);z-index:2}
.card.in .ph .mask{transform:scaleY(0)}
.card .ph img.a{transform:scale(1.14)}
.card.in .ph img.a{transform:scale(1)}
.card.peek .ph img.b{opacity:1}
@media (hover:hover){.card:hover .ph img.b{opacity:1}.card:hover .ph img.a{transform:scale(1.04)}}
.card .tag{position:absolute;z-index:3;left:8px;top:8px;background:var(--bg);color:var(--ink);padding:5px 7px;font:500 9px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.card .hbtn{position:absolute;z-index:3;right:4px;top:4px;width:40px;height:40px;display:flex;align-items:center;justify-content:center;color:#fff}
.hbtn svg{width:19px;height:19px;stroke:currentColor;fill:none;stroke-width:1.5;filter:drop-shadow(0 1px 3px rgba(0,0,0,.35));transition:fill .3s}
.hbtn.on svg{fill:currentColor;animation:bump .5s cubic-bezier(.3,1.6,.4,1)}
.hbtn .burst{position:absolute;inset:0;pointer-events:none}
.hbtn .burst i{position:absolute;left:50%;top:50%;width:4px;height:4px;border-radius:50%;background:#fff;opacity:0}
.hbtn.pop .burst i{animation:burst .6s var(--ease) both}
@keyframes burst{0%{opacity:1;transform:translate(-50%,-50%) rotate(var(--r)) translateY(0)}100%{opacity:0;transform:translate(-50%,-50%) rotate(var(--r)) translateY(-20px)}}
.card .vid{position:absolute;z-index:3;left:8px;bottom:8px;display:none;align-items:center;gap:6px;color:#fff;font:500 10px/1 var(--sans);letter-spacing:.1em}
.card .vid svg{width:12px;height:12px;fill:#fff}
html[data-trade=performer] .card .vid{display:inline-flex}
.meta{padding-top:12px}
.meta .nm{font:400 17px/1.2 var(--serif);margin:6px 0 6px}
html[data-font=b] .meta .nm{font-size:19px;font-weight:500}
.meta .pr{font:400 13px/1.3 var(--sans);color:var(--mute)}

/* editorial band */
.band{position:relative;margin-top:clamp(64px,14vw,140px);height:112vw;max-height:820px;min-height:420px;overflow:hidden;color:#fff;background:#1a1411}
.band img{position:absolute;left:0;width:100%;height:130%;top:-15%;object-fit:cover;will-change:transform}
.band::after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(0,0,0,.55),rgba(0,0,0,.05) 60%)}
.band .in{position:absolute;z-index:2;left:var(--pad);right:var(--pad);bottom:40px}
.band .in .caps{display:block}.band h3{font:400 clamp(34px,10vw,72px)/1.12 var(--serif);margin:.3em 0 .45em}
.roll{overflow:hidden;white-space:nowrap;padding:26px 0 0;margin-top:0}
.roll div{display:inline-block;font:italic 400 clamp(64px,19vw,180px)/1 var(--serif);letter-spacing:-.02em;will-change:transform;color:var(--ink)}
.roll div span{color:transparent;-webkit-text-stroke:1px var(--ink)}
html[data-roll=off] .roll{display:none}

/* collections */
.rail{display:flex;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;padding:0 var(--pad) 8px;scrollbar-width:none;scroll-padding:0 var(--pad)}
.rail::-webkit-scrollbar{display:none}
.coll{flex:none;width:74vw;max-width:360px;scroll-snap-align:start;transition:transform .2s linear}
.coll .ph{aspect-ratio:4/5}
.coll .ph img{transition:transform 1.2s var(--ease)}
.coll:hover .ph img{transform:scale(1.05)}
.coll .num{position:absolute;z-index:2;left:12px;top:12px;color:#fff;font:400 13px/1 var(--serif);letter-spacing:.08em}
.coll .cap{display:flex;justify-content:space-between;align-items:baseline;padding-top:12px}
.coll .cap b{font:400 19px/1.2 var(--serif)}
.rail-foot{display:flex;align-items:center;gap:14px;padding:18px var(--pad) 0}
.rail-foot .track{flex:1;height:1px;background:var(--line);position:relative}
.rail-foot .thumb{position:absolute;left:0;top:-.5px;height:2px;background:var(--ink);width:25%;transition:transform .15s linear}

/* reviews */
.rev{padding:0 var(--pad)}
.qwrap{position:relative;transition:height .5s var(--ease)}
.q{position:absolute;inset:0 0 auto 0;opacity:0;pointer-events:none;transition:opacity .5s var(--ease)}
.q:not(.on) p .w{transition-delay:0s!important}
.q.on{opacity:1;pointer-events:auto}
.q p{font:italic 400 clamp(24px,6.6vw,40px)/1.26 var(--serif);margin:0 0 20px;max-width:24ch}
.q p .w{display:inline-block;opacity:0;transform:translateY(12px);filter:blur(4px);transition:opacity .6s var(--ease),transform .6s var(--ease),filter .6s var(--ease);transition-delay:calc(var(--i) * 32ms)}
.q.on p .w{opacity:1;transform:none;filter:none}
.q .by{opacity:0;transition:opacity .6s .5s}.q.on .by{opacity:1}
.qmark{display:block;width:34px;height:26px;margin:22px 0 12px;background:currentColor;-webkit-mask:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 34 26'%3E%3Cpath d='M0 26V15C0 6 5 1 14 0v5c-5 1-7 4-7 9h7v12zm20 0V15c0-9 5-14 14-15v5c-5 1-7 4-7 9h7v12z'/%3E%3C/svg%3E") center/contain no-repeat;mask:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 34 26'%3E%3Cpath d='M0 26V15C0 6 5 1 14 0v5c-5 1-7 4-7 9h7v12zm20 0V15c0-9 5-14 14-15v5c-5 1-7 4-7 9h7v12z'/%3E%3C/svg%3E") center/contain no-repeat}
.qnav{display:flex;gap:10px;align-items:center;margin-top:10px}
.qnav button{width:44px;height:44px;border:1px solid var(--line);display:flex;align-items:center;justify-content:center;transition:background .3s,color .3s}
.qnav button:hover{background:var(--ink);color:var(--bg)}
.qnav svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.4}
.qnav .ct{margin-left:8px}
.vt{display:flex;gap:14px;align-items:center;margin-top:22px;padding-top:18px;border-top:1px solid var(--line)}
.vt .ph{width:76px;aspect-ratio:3/4;flex:none}
.vt .ph .pl{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;z-index:2}
.vt .ph .pl i{width:30px;height:30px;border-radius:50%;background:rgba(255,255,255,.92);display:flex;align-items:center;justify-content:center}
.vt .ph .pl svg{width:10px;height:10px;fill:#111;margin-left:2px}

/* pricing */
.price{padding:0 var(--pad)}
.row{display:flex;align-items:baseline;gap:10px;padding:18px 0;border-bottom:1px solid var(--line)}
.row .n{font:400 19px/1.25 var(--serif)}
html[data-font=b] .row .n{font-size:21px;font-weight:500}
.row .dots{flex:1;border-bottom:1px dotted var(--mute);opacity:.5;transform:translateY(-4px);transform-origin:left;transition:transform 1.1s var(--ease) var(--d,0s)}
.row.rv:not(.in) .dots{transform:translateY(-4px) scaleX(0)}
.row .v{font:500 13px/1 var(--sans);white-space:nowrap}
.note{color:var(--mute);font-size:13px;margin:16px 0 0;max-width:40ch}

/* story */
.story{padding:0 var(--pad);display:grid;gap:26px}
.story .ph{aspect-ratio:4/5}
.story p{font:400 16px/1.65 var(--sans);margin:0;max-width:44ch}
.story .lead{font:400 clamp(24px,6.4vw,38px)/1.2 var(--serif);max-width:22ch;margin:0}
.mg svg{width:74px;height:74px}
.mg circle{fill:none;stroke:var(--ink);stroke-width:.8;stroke-dasharray:226;stroke-dashoffset:226;transition:stroke-dashoffset 1.8s var(--ease) .2s}
.mg text{font-family:var(--serif);font-size:24px;fill:var(--ink);opacity:0;transition:opacity 1s .9s}
.mg.in circle{stroke-dashoffset:0}.mg.in text{opacity:1}

/* faq */
.faq{padding:0 var(--pad)}
.fq{border-bottom:1px solid var(--line)}
.fq button{width:100%;display:flex;justify-content:space-between;align-items:center;gap:16px;text-align:left;padding:20px 0;font:400 18px/1.3 var(--serif);min-height:44px}
html[data-font=b] .fq button{font-size:20px;font-weight:500}
.fq .pm{flex:none;width:14px;height:14px;position:relative}
.fq .pm::before,.fq .pm::after{content:"";position:absolute;left:0;right:0;top:50%;height:1px;background:currentColor;transition:transform .45s var(--ease)}
.fq .pm::after{transform:rotate(90deg)}.fq.open .pm::after{transform:rotate(0)}
.fq .ans{display:grid;grid-template-rows:0fr;transition:grid-template-rows .55s var(--ease)}
.fq.open .ans{grid-template-rows:1fr}
.fq .ans>div{overflow:hidden}.fq .ans p{margin:0 0 22px;color:var(--mute);max-width:52ch}

/* footer */
footer{margin-top:clamp(56px,11vw,120px);padding:56px var(--pad) calc(90px + env(safe-area-inset-bottom,0px));background:var(--ink);color:var(--bg);--line:color-mix(in srgb,var(--bg) 20%,transparent);--mute:color-mix(in srgb,var(--bg) 62%,transparent)}
footer .ask .ar{border-color:var(--bg)}footer .ask:hover .ar{background:var(--bg);color:var(--ink)}
footer .ask{border-bottom:1px solid var(--line);margin-bottom:34px}
.ask{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:6px 0 40px;font:400 clamp(22px,6vw,34px)/1.2 var(--serif)}
.ask .ar{width:48px;height:48px;border-radius:50%;border:1px solid var(--ink);flex:none;display:flex;align-items:center;justify-content:center;transition:background .4s,color .4s,transform .5s var(--ease)}
.ask:hover .ar{background:var(--ink);color:var(--bg);transform:rotate(-45deg)}
.ask .ar svg{width:18px;height:18px;stroke:currentColor;fill:none;stroke-width:1.4}
.bigwm{font:400 clamp(30px,10.5vw,220px)/1.14 var(--serif);letter-spacing:.01em;text-transform:uppercase;white-space:nowrap;margin:.1em 0 .35em;transition:letter-spacing 1.6s var(--ease)}
.fl{display:flex;flex-wrap:wrap;gap:12px 22px;color:var(--mute)}
.credit{margin-top:28px;color:var(--mute);font-size:12px}

/* menu drawer */
.scrim{position:fixed;inset:0;z-index:40;background:rgba(10,8,7,.5);opacity:0;pointer-events:none;transition:opacity .5s var(--ease)}
.scrim.on{opacity:1;pointer-events:auto}
.drawer{position:fixed;z-index:41;top:0;bottom:0;left:0;width:min(88vw,440px);background:var(--bg);color:var(--ink);transform:translateX(-102%);transition:transform .7s var(--wipe);display:flex;flex-direction:column;padding:calc(18px + env(safe-area-inset-top,0px)) var(--pad) calc(24px + env(safe-area-inset-bottom,0px))}
.drawer.on{transform:none}
.drawer .x{align-self:flex-start;display:inline-flex;gap:10px;align-items:center;min-height:44px}
.drawer nav{margin-top:28px;display:flex;flex-direction:column}
.drawer nav a{font:400 32px/1.25 var(--serif);padding:6px 0;opacity:0;transform:translateX(-18px);transition:opacity .5s var(--ease),transform .6s var(--ease)}
.drawer.on nav a{opacity:1;transform:none;transition-delay:calc(.18s + var(--i) * 45ms)}
.drawer .foot{margin-top:auto;display:flex;flex-direction:column;gap:14px;color:var(--mute)}
.x svg{width:18px;height:18px;stroke:currentColor;stroke-width:1.4;fill:none}

/* look page */
.lp{position:fixed;inset:0;z-index:50;background:var(--bg);color:var(--ink);overflow-y:auto;overscroll-behavior:contain;visibility:hidden;opacity:0}
.lp.on{visibility:visible;opacity:1}
.lp .top{position:sticky;top:0;z-index:3;display:flex;justify-content:space-between;align-items:center;padding:calc(6px + env(safe-area-inset-top,0px)) var(--pad) 6px;color:#fff;transition:background .4s,color .4s}
.lp .top.solid{background:color-mix(in srgb,var(--bg) 94%,transparent);color:var(--ink);box-shadow:0 .5px 0 var(--line);backdrop-filter:blur(12px)}
.lp .top .hbtn{position:static;color:inherit}
.gal{position:relative;margin-top:-56px}
.gal .strip{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}
.gal .strip::-webkit-scrollbar{display:none}
.gal .ph{flex:none;width:100%;scroll-snap-align:start;aspect-ratio:3/4}
.gal .ctr{position:absolute;right:var(--pad);bottom:14px;z-index:2;color:#fff;font:500 11px/1 var(--sans);letter-spacing:.14em}
.gal .dots{position:absolute;left:var(--pad);bottom:16px;display:flex;gap:6px;z-index:2}
.gal .dots i{width:18px;height:1.5px;background:rgba(255,255,255,.45);transition:background .3s,width .4s var(--ease)}
.gal .dots i.on{background:#fff;width:34px}
.lp .body{padding:24px var(--pad) 40px}
.crumb{color:var(--mute)}
.lp h1{font:400 clamp(32px,9vw,56px)/1.04 var(--serif);margin:12px 0 10px;letter-spacing:-.01em}
.lp .from{font:500 13px/1 var(--sans);letter-spacing:.06em;margin-bottom:18px}
.lp .desc{color:var(--mute);margin:0 0 24px;max-width:46ch}
.btn-k{background:var(--ink);color:var(--bg);width:100%}
.btn-k::before{background:var(--accent)}
.btn-k:hover::before{transform:none}
.btn-o{border:1px solid var(--ink);width:100%;margin-top:10px;transition:background .4s,color .4s}
.btn-o:hover{background:var(--ink);color:var(--bg)}
.cred a{border-bottom:1px solid var(--line)}
.cred li{list-style:none;display:flex;justify-content:space-between;gap:12px;padding:6px 0}
.cred ul{padding:0;margin:0 0 20px}
.inc{margin:0 0 20px;padding-left:18px;color:var(--mute)}
.inc li{padding:3px 0}
.also{margin-top:36px}
.also .rail .coll{width:44vw;max-width:220px}
.also .rail .coll .ph{aspect-ratio:3/4}
.fly{position:fixed;z-index:60;object-fit:cover;pointer-events:none;transition:all calc(.75s * var(--k)) var(--wipe)}

/* Eliza panel */
.ez{position:fixed;z-index:70;left:0;right:0;bottom:0;height:min(92svh,760px);background:var(--bg);color:var(--ink);transform:translateY(102%);transition:transform .75s var(--wipe);display:flex;flex-direction:column;box-shadow:0 -1px 0 var(--line)}
.ez.on{transform:none}
.ez .eh{display:flex;align-items:center;gap:12px;padding:18px var(--pad);border-bottom:1px solid var(--line)}
.ez .eh .mono{border-color:var(--ink)}
.ez .eh .t{flex:1}.ez .eh .t b{display:block;font:400 18px/1.2 var(--serif)}
.ez .eh .t span{color:var(--mute);font-size:12px}
.ez .msgs{flex:1;overflow-y:auto;padding:22px var(--pad);display:flex;flex-direction:column;gap:14px}
.m{max-width:86%;opacity:0;transform:translateY(10px);animation:min .6s var(--ease) forwards}
@keyframes min{to{opacity:1;transform:none}}
.m.s{font:400 19px/1.35 var(--serif)}
html[data-font=b] .m.s{font-size:21px}
.m.u{align-self:flex-end;background:var(--soft);padding:10px 14px;font-size:14px}
.m .chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}
.chip{border:1px solid var(--ink);padding:0 14px;min-height:40px;display:inline-flex;align-items:center;font:500 11px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase;transition:background .3s,color .3s}
.chip:hover,.chip.on{background:var(--ink);color:var(--bg)}
.dt{display:flex;gap:8px;margin-top:12px}
.dt input{flex:1;min-height:46px;border:1px solid var(--line);background:transparent;color:var(--ink);font:400 15px var(--sans);padding:0 12px;border-radius:0}
.dt .btn{min-height:46px;padding:0 18px}
.checking{display:inline-flex;gap:6px;align-items:center;color:var(--mute);font-size:13px}
.checking i{width:5px;height:5px;border-radius:50%;background:currentColor;animation:dot 1s infinite}
.checking i:nth-child(2){animation-delay:.15s}.checking i:nth-child(3){animation-delay:.3s}
@keyframes dot{50%{opacity:.2}}
.ez .ef{padding:12px var(--pad) calc(14px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--line);color:var(--mute);font-size:11.5px}

/* prototype tray: outside the design */
.pt{position:fixed;z-index:90;left:12px;bottom:calc(12px + env(safe-area-inset-bottom,0px));font:500 12px/1.2 system-ui,-apple-system,sans-serif;color:#fff}
.pt>button{background:rgba(20,20,20,.78);backdrop-filter:blur(10px);border-radius:999px;padding:9px 13px;letter-spacing:.02em;display:flex;gap:7px;align-items:center;box-shadow:0 2px 10px rgba(0,0,0,.25)}
.pt>button i{width:7px;height:7px;border-radius:50%;background:#7ee0a8}
.pt .pan{position:absolute;left:0;bottom:44px;width:min(300px,calc(100vw - 24px));background:rgba(18,18,18,.94);backdrop-filter:blur(14px);border-radius:14px;padding:12px;display:none;box-shadow:0 10px 40px rgba(0,0,0,.35)}
.pt.open .pan{display:block}
.pt .g{margin-bottom:10px}.pt .g>span{display:block;opacity:.6;margin-bottom:6px;font-size:11px}
.pt .g div{display:flex;flex-wrap:wrap;gap:6px}
.pt .g button{background:rgba(255,255,255,.1);border-radius:8px;padding:7px 9px;font-size:11.5px}
.pt .g button.on{background:#fff;color:#111}
.pt small{display:block;opacity:.55;font-size:10.5px;line-height:1.4}

/* desktop */
@media (min-width:1024px){
  .hd{height:72px}.cats{top:72px;justify-content:center;gap:34px}.segs{top:130px;left:auto;width:220px}
  .grid{grid-template-columns:repeat(4,1fr);gap:48px 18px}
  .copy{left:auto;right:auto;left:50%;transform:translateX(-50%);text-align:center;width:min(900px,80vw)}
  .copy .h1{margin-left:auto;margin-right:auto}
  .coll{width:30vw}
  .cue{display:none}
  .slide img{object-position:var(--dp)!important}
  .band{height:78vh}
  .story{grid-template-columns:5fr 6fr;align-items:center;gap:6vw}
  .story .ph{aspect-ratio:4/5}
  .lp .wrap{display:grid;grid-template-columns:minmax(0,7fr) minmax(0,5fr)}
  .gal{margin-top:-68px}.gal .strip{display:grid;grid-template-columns:1fr 1fr;gap:4px;overflow:visible}
  .gal .dots,.gal .ctr{display:none}
  .lp .body{position:sticky;top:60px;align-self:start;padding:60px 48px}
  .ez{left:auto;top:0;height:auto;width:440px;transform:translateX(102%);box-shadow:-1px 0 0 var(--line)}
  .ez.on{transform:none}
  .price,.faq,.rev{max-width:860px;margin:0 auto}
  .also .rail .coll{width:18vw}
}
@media (prefers-reduced-motion:reduce){
  *,*::before,*::after{animation:none!important;transition:none!important}
  .rv,.card .ph img.a{opacity:1!important;transform:none!important}
  .card .ph .mask{display:none}
  .ln>span,.copy .kick>span,.copy .btn{transform:none!important;opacity:1!important}
  .slide.enter{clip-path:inset(0)}
  .q p .w{opacity:1!important;transform:none!important;filter:none!important}
  .mg circle{stroke-dashoffset:0!important}.mg text{opacity:1!important}
  .tk-track{transform:none!important}
}
`;
