// lib/site/styles/engine.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/engine.css sha256 c69e1561bd053ca271e1147e5ec6c1ae61ff50862c3957c90a2e0f8da435b998 (WEB-3's approved rendition, verbatim).
export const CSS = `:root{--ease:cubic-bezier(.22,.8,.2,1);--wipe:cubic-bezier(.77,0,.18,1);--pad:clamp(18px,4.8vw,44px);--r:0px;--br:0px;--k:1;box-sizing:border-box}
html.calm{--k:.7}html.cinema{--k:1.45}
*,*::before,*::after{box-sizing:inherit}
html,body{margin:0;background:var(--bg);color:var(--ink)}
body{font:400 15px/1.6 var(--sans);-webkit-font-smoothing:antialiased;overflow-x:hidden;transition:background .6s,color .6s}
a{color:inherit;text-decoration:none}button{font:inherit;color:inherit;background:none;border:0;padding:0;cursor:pointer}
img{display:block;max-width:100%}
.ph{position:relative;overflow:hidden;background:var(--soft)}
.ph::before{content:"";position:absolute;inset:-10%;background:var(--lq) center/cover;filter:blur(14px);opacity:.9}
.ph img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
.rv{opacity:0;transform:translateY(calc(24px * var(--k)));transition:opacity calc(.9s * var(--k)) var(--ease),transform calc(.9s * var(--k)) var(--ease);transition-delay:var(--d,0s)}
.rv.in{opacity:1;transform:none}
.ln{display:block;overflow:hidden;padding-bottom:.08em}
.ln>span{display:inline-block;transform:translateY(108%);transition:transform calc(1.05s * var(--k)) var(--ease)}
.in .ln>span,.ln.in>span{transform:none}
/* hearts */
.hbtn{position:relative;width:42px;height:42px;display:inline-flex;align-items:center;justify-content:center;color:inherit}
.hbtn svg,.ib svg{width:19px;height:19px;stroke:currentColor;fill:none;stroke-width:1.5;transition:fill .3s}
.hbtn.on svg{fill:currentColor;animation:bump .5s cubic-bezier(.3,1.6,.4,1)}
@keyframes bump{40%{transform:scale(1.35)}}
.hbtn .burst{position:absolute;inset:0;pointer-events:none}
.hbtn .burst i{position:absolute;left:50%;top:50%;width:4px;height:4px;border-radius:50%;background:currentColor;opacity:0}
.hbtn.pop .burst i{animation:burst .6s var(--ease) both}
@keyframes burst{0%{opacity:1;transform:translate(-50%,-50%) rotate(var(--r)) translateY(0)}100%{opacity:0;transform:translate(-50%,-50%) rotate(var(--r)) translateY(-20px)}}
.ib{display:inline-flex;align-items:center;gap:8px;min-height:44px;min-width:32px}
.heart{position:relative}.heart .n{position:absolute;top:5px;right:-9px;min-width:16px;height:16px;border-radius:8px;background:var(--ink);color:var(--bg);font:600 9px/16px var(--sans);text-align:center;transform:scale(0);transition:transform .45s cubic-bezier(.3,1.6,.4,1)}
.heart.has .n{transform:scale(1)}.heart.bump svg{animation:bump .5s cubic-bezier(.3,1.6,.4,1)}
.emono,.mono{display:inline-flex;width:36px;height:36px;border:1px solid currentColor;border-radius:50%;align-items:center;justify-content:center;font:400 13px/1 var(--serif);letter-spacing:.04em;flex:none}
/* faq */
.fq{border-bottom:1px solid var(--line)}
.fq button{width:100%;display:flex;justify-content:space-between;align-items:center;gap:16px;text-align:left;padding:20px 0;min-height:44px}
.fq .pm{flex:none;width:14px;height:14px;position:relative}
.fq .pm::before,.fq .pm::after{content:"";position:absolute;left:0;right:0;top:50%;height:1px;background:currentColor;transition:transform .45s var(--ease)}
.fq .pm::after{transform:rotate(90deg)}.fq.open .pm::after{transform:rotate(0)}
.fq .ans{display:grid;grid-template-rows:0fr;transition:grid-template-rows .55s var(--ease)}
.fq.open .ans{grid-template-rows:1fr}.fq .ans>div{overflow:hidden}.fq .ans p{margin:0 0 22px;color:var(--mute);max-width:52ch}
/* quotes */
#qwrap{position:relative;transition:height .5s var(--ease)}
.q{position:absolute;inset:0 0 auto 0;opacity:0;pointer-events:none;transition:opacity .5s var(--ease)}
.q.on{opacity:1;pointer-events:auto}
.q .w{display:inline-block;opacity:0;transform:translateY(12px);filter:blur(4px);transition:opacity .6s var(--ease),transform .6s var(--ease),filter .6s var(--ease);transition-delay:calc(var(--i) * 32ms)}
.q.on .w{opacity:1;transform:none;filter:none}.q:not(.on) .w{transition-delay:0s}
.q .by{opacity:0;transition:opacity .6s .5s}.q.on .by{opacity:1}
/* buttons */
.btn{display:inline-flex;align-items:center;justify-content:center;gap:12px;min-height:50px;padding:0 26px;border-radius:var(--br);font:500 11.5px/1 var(--sans);letter-spacing:.16em;text-transform:uppercase;position:relative;overflow:hidden;isolation:isolate;transition:color .45s,background .45s,border-color .45s}
.btn .ar{transition:transform .45s var(--ease)}.btn:hover .ar{transform:translateX(5px)}
/* scrim + drawer */
.scrim{position:fixed;inset:0;z-index:40;background:rgba(8,6,5,.55);opacity:0;pointer-events:none;transition:opacity .5s var(--ease)}
.scrim.on{opacity:1;pointer-events:auto}
.drawer{position:fixed;z-index:41;top:0;bottom:0;left:0;width:min(88vw,440px);background:var(--bg);color:var(--ink);transform:translateX(-102%);transition:transform .7s var(--wipe);display:flex;flex-direction:column;padding:calc(18px + env(safe-area-inset-top,0px)) var(--pad) calc(24px + env(safe-area-inset-bottom,0px))}
.drawer.on{transform:none}
.drawer .x{align-self:flex-start;display:inline-flex;gap:10px;align-items:center;min-height:44px;font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.x svg,.back svg{width:18px;height:18px;stroke:currentColor;stroke-width:1.4;fill:none}
#dnav{margin-top:26px;display:flex;flex-direction:column;flex-shrink:0}
.drawer{overflow-y:auto;overscroll-behavior:contain}.dfoot{flex-shrink:0;padding-top:24px}
#dnav a{font:400 32px/1.25 var(--serif);padding:6px 0;opacity:0;transform:translateX(-18px);transition:opacity .5s var(--ease),transform .6s var(--ease);display:flex;align-items:baseline;gap:14px}
#dnav a em{font:500 10px/1 var(--sans);letter-spacing:.12em;font-style:normal;opacity:.5;width:18px}
.drawer.on #dnav a{opacity:1;transform:none;transition-delay:calc(.18s + var(--i) * 45ms)}
.dfoot{margin-top:auto;display:flex;flex-direction:column;gap:12px;color:var(--mute);font:500 11px/1.4 var(--sans);letter-spacing:.12em;text-transform:uppercase}
/* look page */
.lp{position:fixed;inset:0;z-index:50;background:var(--bg);color:var(--ink);overflow-y:auto;overscroll-behavior:contain;visibility:hidden;opacity:0;transition:opacity .45s var(--ease),visibility 0s .45s}
.lp.on{visibility:visible;opacity:1;transition:opacity .45s var(--ease)}
.lp.closing{opacity:0}
.lp .top{position:sticky;top:0;z-index:3;display:flex;justify-content:space-between;align-items:center;padding:calc(6px + env(safe-area-inset-top,0px)) var(--pad) 6px;color:#fff;transition:background .4s,color .4s}
.lp .top.solid{background:color-mix(in srgb,var(--bg) 92%,transparent);color:var(--ink);box-shadow:0 .5px 0 var(--line);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}
.back{display:inline-flex;align-items:center;gap:8px;min-height:44px;font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.gal{position:relative;margin-top:-56px}
.gal .strip{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}
.gal .strip::-webkit-scrollbar{display:none}
.gal .ph{flex:none;width:100%;scroll-snap-align:start;aspect-ratio:3/4}
.gal .ctr{position:absolute;right:var(--pad);bottom:14px;z-index:2;color:#fff;font:500 11px/1 var(--sans);letter-spacing:.14em}
.gal .dots{position:absolute;left:var(--pad);bottom:16px;display:flex;gap:6px;z-index:2}
.gal .dots i{width:18px;height:1.5px;background:rgba(255,255,255,.45);transition:background .3s,width .4s var(--ease)}
.gal .dots i.on{background:#fff;width:34px}
.lp .body{padding:26px var(--pad) 48px}
.crumb{color:var(--mute);font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.lpt{font:400 clamp(32px,9vw,56px)/1.05 var(--serif);margin:12px 0 10px}
.from{font:500 13px/1 var(--sans);letter-spacing:.06em;margin-bottom:18px}
.desc{color:var(--mute);margin:0 0 24px;max-width:46ch}
.lp .btn{width:100%}.lp .btn-alt{margin-top:10px}
.blk{margin-top:28px}.bh{font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase;margin-bottom:12px}
.inc{margin:0;padding-left:18px;color:var(--mute)}.inc li{padding:3px 0}
.cred{list-style:none;margin:0;padding:0}.cred li{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid var(--line)}
.cred a{border-bottom:1px solid currentColor}
.arail{display:flex;gap:10px;overflow-x:auto;scrollbar-width:none;padding-bottom:4px}.arail::-webkit-scrollbar{display:none}
.acard{flex:none;width:42vw;max-width:200px}.acard .ph{aspect-ratio:3/4;border-radius:var(--r)}.acard b{display:block;font:400 15px/1.3 var(--serif);margin-top:8px;font-weight:400}
.fly{position:fixed;z-index:60;object-fit:cover;pointer-events:none;transition:all calc(.75s * var(--k)) var(--wipe);border-radius:var(--r)}
/* Eliza */
.ez{position:fixed;z-index:70;left:0;right:0;bottom:0;height:min(90svh,740px);background:var(--bg);color:var(--ink);transform:translateY(102%);transition:transform .75s var(--wipe);display:flex;flex-direction:column;border-radius:var(--r) var(--r) 0 0}
.ez.on{transform:none}
.ez .eh{display:flex;align-items:center;gap:12px;padding:18px var(--pad);border-bottom:1px solid var(--line)}
.ez .t{flex:1}.ez .t b{display:block;font:400 18px/1.2 var(--serif)}.ez .t span{color:var(--mute);font-size:12px}
.ez .x{width:44px;height:44px;display:flex;align-items:center;justify-content:center}
.msgs{flex:1;overflow-y:auto;padding:22px var(--pad);display:flex;flex-direction:column;gap:14px}
.m{max-width:88%;opacity:0;transform:translateY(10px);animation:min .6s var(--ease) forwards}
@keyframes min{to{opacity:1;transform:none}}
.m.s{font:400 19px/1.38 var(--serif)}
.m.u{align-self:flex-end;background:var(--soft);padding:10px 14px;font-size:14px;border-radius:var(--r)}
.chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}
.chip{border:1px solid var(--ink);border-radius:var(--br);padding:0 14px;min-height:40px;display:inline-flex;align-items:center;font:500 11px/1 var(--sans);letter-spacing:.12em;text-transform:uppercase;transition:background .3s,color .3s}
.chip:hover,.chip.on{background:var(--ink);color:var(--bg)}
.dt{display:flex;gap:8px;margin-top:12px}
.dt input{flex:1;min-width:0;min-height:48px;border:1px solid var(--line);background:transparent;color:var(--ink);font:400 15px var(--sans);padding:0 12px;border-radius:var(--br);color-scheme:inherit}
.dt .btn{min-height:48px;padding:0 18px;width:auto}
.checking{display:inline-flex;gap:6px;align-items:center;color:var(--mute);font:400 13px var(--sans)}
.checking i{width:5px;height:5px;border-radius:50%;background:currentColor;animation:dot 1s infinite}
.checking i:nth-child(2){animation-delay:.15s}.checking i:nth-child(3){animation-delay:.3s}
@keyframes dot{50%{opacity:.2}}
.ef{padding:12px var(--pad) calc(14px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--line);color:var(--mute);font-size:11.5px}
/* prototype tray */
.pt{position:fixed;z-index:90;left:12px;bottom:calc(12px + env(safe-area-inset-bottom,0px));font:500 12px/1.2 system-ui,-apple-system,sans-serif;color:#fff}
.pt>button{background:rgba(20,20,20,.8);backdrop-filter:blur(10px);border-radius:999px;padding:9px 13px;display:flex;gap:7px;align-items:center;box-shadow:0 2px 10px rgba(0,0,0,.25);color:#fff}
.pt>button i{width:7px;height:7px;border-radius:50%;background:#7ee0a8}
.pt .pan{position:absolute;left:0;bottom:44px;width:min(310px,calc(100vw - 24px));max-height:70vh;overflow:auto;background:rgba(18,18,18,.95);backdrop-filter:blur(14px);border-radius:14px;padding:12px;display:none;box-shadow:0 10px 40px rgba(0,0,0,.35)}
.pt.open .pan{display:block}.pt .g{margin-bottom:10px}.pt .g>span{display:block;opacity:.6;margin-bottom:6px;font-size:11px}
.pt .g div{display:flex;flex-wrap:wrap;gap:6px}.pt .g button{background:rgba(255,255,255,.1);border-radius:8px;padding:7px 9px;font-size:11.5px;color:#fff}
.pt .g button.on{background:#fff;color:#111}.pt small{display:block;opacity:.55;font-size:10.5px;line-height:1.4}
.vidtag{display:none}html[data-trade=performer] .vidtag{display:inline-flex}
@media (min-width:1024px){
 .lp .wrap{display:grid;grid-template-columns:minmax(0,7fr) minmax(0,5fr)}
 .gal .strip{display:grid;grid-template-columns:1fr 1fr;gap:4px;overflow:visible}.gal .dots,.gal .ctr{display:none}
 .lp .body{position:sticky;top:60px;align-self:start;padding:60px 48px}
 .ez{left:auto;top:0;height:auto;width:440px;transform:translateX(102%);border-radius:0}.ez.on{transform:none}
}
@media (prefers-reduced-motion:reduce){
 *,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}
 .rv,.ln>span,.q .w{opacity:1!important;transform:none!important;filter:none!important}
}
`;
