// lib/site/styles/gallery.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/gallery.html sha256 80a321077afad137b018be20d076eedbb6dade50a1b8e2f81b40c0e6df8b1a5b (WEB-3's approved rendition, verbatim).
export const CSS = `
:root{--bg:#fbfbf9;--ink:#141414;--mute:#6e6e6a;--line:rgba(20,20,20,.14);--soft:#efefeb;--accent:#141414;--on-accent:#fbfbf9;--mat:#ffffff;--frame:#1b1b1b;--shadow:0 22px 40px -18px rgba(0,0,0,.35),0 4px 10px -4px rgba(0,0,0,.18);
 --serif:"Instrument Serif","Bodoni Moda",Georgia,serif;--sans:"Instrument Sans","Helvetica Neue",Arial,sans-serif}
html[data-pal=grey]{--bg:#e6e5e0;--soft:#dcdbd5;--mute:#5f5e59}
html[data-pal=night]{--bg:#1b1b1a;--ink:#ecebe6;--mute:#9a9994;--line:rgba(236,235,230,.14);--soft:#252524;--accent:#ecebe6;--on-accent:#1b1b1a;--mat:#f4f2ec;--frame:#0c0c0c;--shadow:0 30px 60px -20px rgba(0,0,0,.8)}
html[data-font=b]{--serif:"Bodoni Moda",Didot,serif}
html[data-pal=night] .frame::after{content:"";position:absolute;left:-30%;right:-30%;top:-60%;height:80%;background:radial-gradient(ellipse at 50% 100%,rgba(255,240,210,.18),transparent 70%);pointer-events:none}
.lbl{display:block;font:400 12px/1.5 var(--sans);color:var(--mute)}.lbl b{display:block;color:var(--ink);font-weight:500}
.lbl i{font-family:var(--serif);font-size:15px;color:var(--ink)}
/* header */
.hd{position:fixed;inset:0 0 auto 0;z-index:30;height:58px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 var(--pad);font:500 12.5px/1 var(--sans);transition:background .4s}
.hd.solid{background:color-mix(in srgb,var(--bg) 90%,transparent);backdrop-filter:blur(10px);box-shadow:0 1px 0 var(--line)}
.hd .l{justify-self:start;display:flex;gap:6px;align-items:center}.hd .r{justify-self:end;display:flex;gap:14px;align-items:center}
.wmt{font:500 13px/1 var(--sans);letter-spacing:.02em;white-space:nowrap}.hd .mono{display:none}.hd.use-mono .wmt{display:none}.hd.use-mono .mono{display:inline-flex}
.enq{font:500 12.5px/1 var(--sans);border-bottom:1px solid currentColor;padding-bottom:2px}.ml{font:500 12.5px var(--sans)}
.hd .r .heart{display:none}
/* frames */
.frame{position:relative;background:var(--mat);padding:7%;border:3px solid var(--frame);box-shadow:var(--shadow)}
.frame .ph{aspect-ratio:3/4;background:var(--soft)}
.hang{transform-origin:50% -40px}
.hang.rv{opacity:0;transform:translateY(-26px) rotate(-3deg)}
.hang.rv.in{opacity:1;animation:swing calc(2.2s * var(--k)) cubic-bezier(.25,.8,.3,1) both;transform:none}
@keyframes swing{0%{transform:translateY(-26px) rotate(-3deg);opacity:0}25%{opacity:1;transform:translateY(0) rotate(2deg)}45%{transform:rotate(-1.2deg)}65%{transform:rotate(.6deg)}82%{transform:rotate(-.25deg)}100%{transform:none}}
/* cover: walk up to the painting */
.enter{position:relative;height:250svh}
.enter .stage{position:sticky;top:0;height:100svh;overflow:hidden;display:grid;grid-template-rows:auto minmax(0,1fr) auto;gap:clamp(12px,3vh,28px);padding:calc(72px + env(safe-area-inset-top,0px)) var(--pad) calc(18px + env(safe-area-inset-bottom,0px))}
.enter .head{position:relative;z-index:3;will-change:transform,opacity}
.enter .head h1{font:400 clamp(40px,min(13vw,11vh),150px)/1.1 var(--serif);margin:0;letter-spacing:-.01em}
.enter .head p{margin:12px 0 0;font:400 13px/1.5 var(--sans);color:var(--mute);max-width:32ch}
.enter .big{position:relative;z-index:2;min-height:0;display:flex;align-items:center;justify-content:center;will-change:transform}
.enter #bigh{height:100%;max-width:100%;aspect-ratio:.8;display:flex}
.enter .frame{height:100%;width:100%;display:flex}.enter .frame .ph{flex:1;aspect-ratio:auto}
.enter .big .frame{transition:padding .2s linear,border-color .2s linear}
.enter .foot{display:flex;justify-content:space-between;align-items:flex-end;gap:12px 20px;flex-wrap:wrap;position:relative;z-index:3;will-change:transform,opacity}
.enter .wl{text-align:right;margin-left:auto}
.enter .hint{font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase;display:flex;align-items:center;gap:10px}
.enter .hint i{width:34px;height:1px;background:currentColor;transform-origin:left;animation:hint 2s var(--ease) infinite}
@keyframes hint{0%{transform:scaleX(0)}60%{transform:scaleX(1)}100%{transform:scaleX(1);opacity:0}}
.enter .over{position:absolute;inset:0;z-index:4;display:flex;flex-direction:column;justify-content:flex-end;padding:0 var(--pad) calc(46px + env(safe-area-inset-bottom,0px));color:#fff;opacity:0;pointer-events:none;background:linear-gradient(to top,rgba(0,0,0,.55),transparent 50%)}
.enter .over h2{font:400 clamp(40px,min(12vw,13vh),120px)/1.14 var(--serif);margin:12px 0 20px}
.enter .over .btn{background:#fff;color:#111;align-self:flex-start;pointer-events:auto}
/* exhibition */
section{padding:clamp(56px,12vw,120px) 0 0}
.sh{padding:0 var(--pad);margin-bottom:34px;display:flex;justify-content:space-between;align-items:flex-end;gap:12px}
.sh h2{font:400 clamp(36px,10.5vw,96px)/1.1 var(--serif);margin:8px 0 0;letter-spacing:-.01em}
.ex{display:flex;flex-direction:column;gap:clamp(56px,14vw,140px);padding:0 var(--pad)}
.card{display:grid;gap:14px;align-items:end;position:relative}
.card .frame{width:var(--w,78%)}
.card:nth-child(3n+1){--w:84%}.card:nth-child(3n+2){--w:64%;justify-items:end}.card:nth-child(3n){--w:74%;padding-left:10%}
.card:nth-child(3n+2) .lbl{text-align:right}
.card .frame .ph img{transition:transform 1.4s var(--ease)}.card:hover .frame .ph img{transform:scale(1.03)}
.card .row1{display:flex;gap:14px;align-items:flex-start;justify-content:space-between}
.card .no{font:400 12px/1 var(--sans);color:var(--mute)}
.card .hbtn{margin-top:-10px}
.card .vidtag{position:absolute;z-index:3;left:50%;top:40%;transform:translate(-50%,-50%);width:54px;height:54px;border-radius:50%;background:rgba(255,255,255,.9);align-items:center;justify-content:center}
.card .vidtag svg{width:14px;height:14px;fill:#111;margin-left:3px}
/* sideways rail on a wire */
.side{position:relative;height:320svh;margin-top:clamp(56px,12vw,120px)}
.side .stage{position:sticky;top:0;height:100svh;overflow:hidden;display:flex;flex-direction:column;justify-content:center}
.side .t{padding:0 var(--pad);margin-bottom:5vh}
.side .t h2{font:400 clamp(34px,min(10.5vw,8vh),96px)/1.1 var(--serif);margin:8px 0 0}
.wire{display:none}
.track{position:relative;margin-top:10vh}.track::before{content:"";position:absolute;left:-50vw;width:600vw;top:-8vh;height:1px;background:var(--line)}
.track{display:flex;gap:18vw;padding:0 var(--pad);will-change:transform;align-items:flex-start}
.hung{flex:none;width:min(58vw,420px,calc((100svh - 340px) * .62));position:relative}
.hung::before,.hung::after{content:"";position:absolute;top:-8vh;height:8vh;width:1px;background:var(--mute);opacity:.6}
.hung::before{left:30%;transform:rotate(12deg);transform-origin:bottom}.hung::after{right:30%;transform:rotate(-12deg);transform-origin:bottom}
.hung:nth-child(odd){margin-top:4vh}.hung .frame .ph{aspect-ratio:4/5}.hung .lbl{margin-top:14px}
.hung .frame{animation:sway 6s ease-in-out infinite alternate;transform-origin:50% -8vh}
.hung:nth-child(2) .frame{animation-delay:-2s}.hung:nth-child(3) .frame{animation-delay:-4s}
@keyframes sway{from{transform:rotate(-.6deg)}to{transform:rotate(.6deg)}}
.count{padding:0 var(--pad);margin-top:4vh;font:500 12px var(--sans);display:flex;gap:10px;align-items:center}.count .bar{width:120px;height:1px;background:var(--line);position:relative}.count .bar b{position:absolute;inset:0;background:var(--ink);transform-origin:left;transform:scaleX(var(--p,0))}
/* wall text */
.rev{padding:0 var(--pad);max-width:900px}
.q p{font:italic 400 clamp(28px,8vw,58px)/1.2 var(--serif);margin:0 0 18px;letter-spacing:-.01em}
.q .by{font:500 12px var(--sans);color:var(--mute)}
.qnav{display:flex;gap:18px;margin-top:22px;font:500 12px var(--sans)}.qnav button{border-bottom:1px solid currentColor;padding:6px 0}
.cat{padding:0 var(--pad);max-width:900px}
.row{display:grid;grid-template-columns:34px 1fr auto;gap:10px;align-items:baseline;padding:16px 0;border-top:1px solid var(--line)}
.row .no{font:400 12px var(--sans);color:var(--mute)}.row .n{font:400 21px/1.25 var(--serif)}.row .v{font:500 12.5px var(--sans)}
.note{color:var(--mute);font-size:12.5px;margin:10px 0 0;border-top:1px solid var(--line);padding-top:14px}
.story{padding:0 var(--pad);display:grid;gap:26px}.story .frame{width:72%}.story .lead{font:400 clamp(28px,8vw,52px)/1.18 var(--serif);margin:10px 0 14px}.story p{color:var(--mute);max-width:44ch;margin:0}
.faq{padding:0 var(--pad);max-width:900px}.fq button{font:400 21px/1.25 var(--serif)}
footer{margin-top:clamp(70px,14vw,140px);padding:30px var(--pad) calc(90px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--line)}
.ask{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;width:100%;text-align:left}
.ask .t{font:italic 400 clamp(34px,10vw,90px)/1.12 var(--serif)}
.ask .go{flex:none;width:56px;height:56px;border-radius:50%;background:var(--ink);color:var(--bg);display:flex;align-items:center;justify-content:center;transition:transform .5s var(--ease)}.ask:hover .go{transform:rotate(-45deg)}
.fname{font:400 60px/1.15 var(--serif);white-space:nowrap;margin:60px 0 26px}
.fl{display:flex;flex-wrap:wrap;gap:10px 22px;font:500 12.5px var(--sans)}.credit{margin-top:20px;color:var(--mute);font-size:12px}
/* chrome dress: wall panel */
.lp{transform:translateX(100%);opacity:1;visibility:hidden;transition:transform .85s var(--wipe),visibility 0s .85s}
.lp.on{transform:none;visibility:visible;opacity:1;transition:transform .85s var(--wipe)}.lp.closing{transform:translateX(100%);opacity:1}
.lp .top{color:var(--ink)}.gal{margin-top:0}.gal .strip .ph{background:var(--soft)}
.lpt{font-family:var(--serif)}.btn{text-transform:none;letter-spacing:.01em;font:500 13.5px/1 var(--sans)}
.btn-main{background:var(--ink);color:var(--bg)}.btn-alt{border:1px solid var(--ink)}
.drawer{width:100vw;transform:translateY(-102%)}.drawer.on{transform:none}
#dnav a{font:400 clamp(36px,10vw,72px)/1.1 var(--serif);transform:translateY(16px)}#dnav a em{font:500 11px var(--sans);opacity:.5}
.chip{text-transform:none;letter-spacing:0;font:500 12.5px var(--sans)}
.gal .dots i{background:rgba(0,0,0,.2)}.gal .dots i.on{background:var(--ink)}.gal .ctr{color:var(--ink)}
@media (min-width:700px){.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}}
@media (min-width:1024px){
 .ex{display:grid;grid-template-columns:repeat(12,1fr);gap:120px 2vw;max-width:1400px;margin:0 auto}
 .card{grid-column:span 5}.card:nth-child(4n+2){grid-column:8 / span 4;margin-top:140px}.card:nth-child(4n+3){grid-column:2 / span 4}.card:nth-child(4n){grid-column:7 / span 6;margin-top:80px}
 .card .frame{width:100%}.card:nth-child(3n){padding-left:0}
 .hung{width:min(24vw,calc((100svh - 340px) * .62))}.track{gap:9vw}.story{grid-template-columns:5fr 7fr;align-items:center;max-width:1300px;margin:0 auto}.story .frame{width:80%}
}
@media (prefers-reduced-motion:reduce){.enter,.side{height:auto}.enter .stage,.side .stage{position:relative;height:auto;padding:100px 0 40px}.enter .over{display:none}.hang.rv{opacity:1!important;transform:none!important;animation:none!important}.hung .frame{animation:none}.track{flex-wrap:wrap;gap:40px}}
`;
