// lib/site/styles/heritage.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/heritage.html sha256 7c5f3be68b70a321e320005d2aa8613f85ce407247cf294c0cb93314baf20ed6 (WEB-3's approved rendition, verbatim).
export const CSS = `
@property --j{syntax:'<percentage>';inherits:false;initial-value:0%}
:root{--bg:#f6efe3;--ink:#3b0f0f;--mute:#7a5a4f;--line:rgba(59,15,15,.16);--soft:#eee3d2;--accent:#d98b12;--verm:#b8321f;--on-accent:#fff8ec;--deep:#3b0f0f;--on-deep:#f6e6c8;--atx:#955f0c;--atd:#d98b12;
 --serif:"Marcellus","Cormorant Garamond",Georgia,serif;--sans:"Mulish","Helvetica Neue",sans-serif;--arch:50% 50% 0 0 / 38% 38% 0 0;--br:2px}
html[data-pal=peacock]{--bg:#f1efe6;--ink:#0f3b3a;--mute:#4f6a66;--line:rgba(15,59,58,.16);--soft:#e5e3d6;--accent:#b88a2e;--verm:#0f5c57;--deep:#0c3432;--on-deep:#ecdcb4;--atx:#876522;--atd:#be8f30}
html[data-pal=rani]{--bg:#fbf1ee;--ink:#4a0d2b;--mute:#855a68;--line:rgba(74,13,43,.15);--soft:#f3e3de;--accent:#e08a1e;--verm:#b0205e;--deep:#4a0d2b;--on-deep:#f8dcc0;--atx:#9a5f15;--atd:#e08a1e}
html[data-font=b]{--serif:"Cormorant Garamond",Georgia,serif}
html[data-texture=on] body{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='300'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.75' numOctaves='3'/%3E%3CfeColorMatrix values='0 0 0 0 .35 0 0 0 0 .22 0 0 0 0 .12 0 0 0 .07 0'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}
.caps{font:600 10.5px/1.4 var(--sans);letter-spacing:.24em;text-transform:uppercase;color:var(--atx)}
.band-top{height:12px;background:var(--verm);-webkit-mask:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='12'%3E%3Cpath d='M0 0h24v4H0zM12 5l5 3.5-5 3.5-5-3.5z'/%3E%3C/svg%3E") repeat-x;mask:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='12'%3E%3Cpath d='M0 0h24v4H0zM12 5l5 3.5-5 3.5-5-3.5z'/%3E%3C/svg%3E") repeat-x}
/* header */
.hd{position:sticky;top:0;z-index:30;height:62px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 var(--pad);background:transparent;transition:background .5s,box-shadow .5s}
.hd.solid{background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(10px);box-shadow:0 1px 0 var(--line)}
.hd .l{justify-self:start;display:flex;gap:8px;align-items:center}.hd .r{justify-self:end;display:flex;gap:14px;align-items:center}
.wm{display:flex;flex-direction:column;align-items:center}
.wmt{font:400 18px/1 var(--serif);letter-spacing:.2em;text-transform:uppercase;white-space:nowrap;padding-left:.2em}
.hd .mono{display:none;border-color:var(--accent);color:var(--ink)}.hd.use-mono .wmt{display:none}.hd.use-mono .mono{display:inline-flex}
.enq{font:600 10.5px/1 var(--sans);letter-spacing:.2em;text-transform:uppercase;padding:8px 0 6px;border-bottom:1.5px solid var(--accent)}
.hd .r .heart{display:none}.ml{display:none;font:600 10.5px/1 var(--sans);letter-spacing:.2em;text-transform:uppercase}
/* ornament + rosette */
.orn{display:block;width:min(240px,64vw);height:24px;margin:0 auto;overflow:visible}
.orn path,.orn circle{fill:none;stroke:var(--accent);stroke-width:1.2;stroke-dasharray:300;stroke-dashoffset:300;transition:stroke-dashoffset 2.2s var(--ease) var(--d,0s)}
.orn.in path,.orn.in circle,.cover.go .orn path,.cover.go .orn circle{stroke-dashoffset:0}
.rosette{position:absolute;z-index:0;left:50%;top:46%;width:150vw;max-width:1100px;aspect-ratio:1;transform:translate(-50%,-50%);opacity:.22;pointer-events:none;animation:spin calc(140s / var(--k)) linear infinite}
.rosette path,.rosette circle{fill:none;stroke:var(--accent);stroke-width:.6}
@keyframes spin{to{transform:translate(-50%,-50%) rotate(360deg)}}
/* cover */
.cover{position:relative;padding:10px var(--pad) 40px;text-align:center;overflow:hidden;display:flex;flex-direction:column}
.cover .archw{order:-1;margin-top:8px}
.cover .txt>.caps{display:block;margin-top:18px}
.ctitle{margin-top:20px!important}
.cover>*{position:relative;z-index:1}
.cover>.rosette{position:absolute;z-index:0}
.cover .caps{opacity:0;transition:opacity 1.2s ease .2s}.cover.go .caps{opacity:1}
.archw{position:relative;width:min(80vw,560px);aspect-ratio:3/4.1;margin:18px auto 0;border-radius:var(--arch);overflow:hidden;background:var(--soft);box-shadow:0 0 0 1px var(--accent),0 0 0 7px var(--bg),0 0 0 8px color-mix(in srgb,var(--accent) 60%,transparent)}
.archw .sl{position:absolute;inset:0;opacity:0;transition:opacity 1.2s ease}.archw .sl.on{opacity:1}
.archw .sl img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transform:scale(1.08);transition:transform 9s ease-out}.archw .sl.on img{transform:scale(1)}
.jaali{position:absolute;inset:0;z-index:2;pointer-events:none;background:var(--jl) center/44px;--j:0%;
 -webkit-mask-image:radial-gradient(circle at 50% 50%,transparent var(--j),#000 calc(var(--j) + 18%));mask-image:radial-gradient(circle at 50% 50%,transparent var(--j),#000 calc(var(--j) + 18%));transition:--j calc(2s * var(--k)) cubic-bezier(.4,.1,.2,1)}
.open .jaali,.jaali.open{--j:120%}
.jaali.shut{--j:0%;transition:--j .9s cubic-bezier(.6,0,.8,.4)}
.ctitle{font:400 clamp(34px,10vw,78px)/1.08 var(--serif);margin:26px 0 14px;color:var(--ink)}
.cover .orn{margin-bottom:22px}
.btn-v{background:var(--verm);color:var(--on-accent);box-shadow:inset 0 0 0 3px var(--verm),inset 0 0 0 4px color-mix(in srgb,var(--on-accent) 55%,transparent)}
.btn-v:hover{background:var(--deep)}
.cover .btn-v{opacity:0;transform:translateY(12px);transition:opacity .9s ease 1s,transform .9s var(--ease) 1s,background .4s}.cover.go .btn-v{opacity:1;transform:none}
.pips{display:flex;justify-content:center;gap:10px;margin-top:22px}.pips button{width:10px;height:10px;transform:rotate(45deg);border:1px solid var(--accent);transition:background .4s}.pips button.on{background:var(--accent)}
/* sections */
section{padding:clamp(48px,11vw,110px) 0 0}
.sh{text-align:center;padding:0 var(--pad);margin-bottom:30px}
.sh h2{font:400 clamp(30px,8.6vw,62px)/1.1 var(--serif);margin:10px 0 16px}
/* looks: arch windows */
.grid{display:grid;grid-template-columns:1fr 1fr;gap:34px 14px;padding:0 var(--pad)}
.card{display:block;text-align:center}.card:nth-child(even){margin-top:46px}
.card .ph{aspect-ratio:3/4.4;border-radius:var(--arch);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 70%,transparent)}
.card .ph img{transition:transform 1.4s var(--ease)}.card:hover .ph img{transform:scale(1.05)}
.card .hbtn{position:absolute;z-index:3;right:6px;bottom:6px;background:color-mix(in srgb,var(--bg) 88%,transparent);border-radius:50%;width:38px;height:38px;color:var(--verm)}
.card .cat{display:block;margin-top:14px}.card .nm{font:400 18px/1.25 var(--serif);margin:6px 0 4px}.card .pr{color:var(--mute);font-size:13px}
.card .vidtag{position:absolute;z-index:3;left:50%;top:22%;transform:translateX(-50%);width:48px;height:48px;border-radius:50%;background:color-mix(in srgb,var(--bg) 85%,transparent);align-items:center;justify-content:center;color:var(--verm)}
.card .vidtag svg{width:14px;height:14px;fill:currentColor;margin-left:3px}
/* craft band */
.craft{position:relative;margin:clamp(56px,12vw,120px) var(--pad) 0;border-radius:var(--arch);overflow:hidden;aspect-ratio:3/3.6;max-height:760px;color:#fff8ec}
.craft img{position:absolute;inset:-12% 0;width:100%;height:124%;object-fit:cover;will-change:transform}
.craft::after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(40,10,5,.7),transparent 55%)}
.craft .in2{position:absolute;z-index:3;left:0;right:0;bottom:34px;text-align:center;padding:0 20px}
.craft h3{font:400 clamp(30px,9vw,64px)/1.08 var(--serif);margin:8px 0 0}
.craft .caps{color:#f5c56b}
/* collections */
.rail{display:flex;gap:16px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:6px var(--pad) 8px;scroll-padding:0 var(--pad)}.rail::-webkit-scrollbar{display:none}
.coll{flex:none;width:62vw;max-width:300px;scroll-snap-align:start;text-align:center}
.coll .fr{padding:8px;border:1px solid color-mix(in srgb,var(--accent) 70%,transparent);border-radius:var(--arch)}
.coll .ph{aspect-ratio:3/4.3;border-radius:var(--arch)}
.coll b{display:block;font:400 20px/1.2 var(--serif);font-weight:400;margin-top:14px}.coll span{color:var(--mute);font-size:12.5px}
/* reviews on deep band */
#reviews{background:var(--deep);color:var(--on-deep);margin-top:clamp(56px,12vw,120px);padding:clamp(56px,12vw,110px) var(--pad) clamp(48px,10vw,90px);text-align:center}
#reviews .caps,footer .caps{color:var(--atd)}
.q p{font:400 clamp(24px,6.6vw,40px)/1.3 var(--serif);margin:18px auto 20px;max-width:26ch}
.q .by{font:600 10.5px/1.4 var(--sans);letter-spacing:.2em;text-transform:uppercase;color:var(--atd)}
.qnav{display:flex;justify-content:center;gap:16px;align-items:center;margin-top:26px;font:600 11px var(--sans);letter-spacing:.2em}
.qnav button{width:44px;height:44px;border:1px solid color-mix(in srgb,var(--on-deep) 30%,transparent);transform:rotate(45deg) scale(.8);display:flex;align-items:center;justify-content:center}
.qnav svg{width:14px;height:14px;stroke:currentColor;fill:none;stroke-width:1.4;transform:rotate(-45deg)}
#reviews .orn path,#reviews .orn circle{stroke:var(--accent)}
/* pricing card */
.card-frame{position:relative;margin:0 var(--pad);padding:34px 22px 26px;border:1px solid color-mix(in srgb,var(--accent) 70%,transparent);outline:1px solid color-mix(in srgb,var(--accent) 35%,transparent);outline-offset:-7px;max-width:720px}
@media (min-width:760px){.card-frame{margin:0 auto}}
.corner{position:absolute;width:26px;height:26px;fill:none;stroke:var(--accent);stroke-width:1.2}
.corner.tl{top:-1px;left:-1px}.corner.tr{top:-1px;right:-1px;transform:scaleX(-1)}.corner.bl{bottom:-1px;left:-1px;transform:scaleY(-1)}.corner.br{bottom:-1px;right:-1px;transform:scale(-1)}
.row{display:flex;align-items:baseline;gap:10px;padding:13px 0}
.row .n{font:400 18px/1.3 var(--serif)}.row .dots{flex:1;border-bottom:1.5px dotted var(--accent);opacity:.7;transform-origin:left;transition:transform 1.2s var(--ease) var(--d,0s)}
.row.rv:not(.in) .dots{transform:scaleX(0)}.row .v{font:600 13px/1 var(--sans);white-space:nowrap;color:var(--verm)}
.note{color:var(--mute);font-size:13px;text-align:center;margin:16px 0 0}
/* story */
.story{display:grid;gap:26px;padding:0 var(--pad);text-align:center}
.story .ph{width:min(76vw,420px);margin:0 auto;aspect-ratio:3/4.2;border-radius:var(--arch)}
.story .lead{font:400 clamp(24px,6.6vw,40px)/1.25 var(--serif);margin:10px auto 16px;max-width:22ch}.story p{color:var(--mute);max-width:44ch;margin:0 auto}
.faq{padding:0 var(--pad);max-width:760px;margin:0 auto}.fq button{font:400 19px/1.3 var(--serif)}.fq .pm{color:var(--verm)}
footer{margin-top:clamp(64px,13vw,130px);background:var(--deep);color:var(--on-deep);text-align:center;padding:56px var(--pad) calc(90px + env(safe-area-inset-bottom,0px));position:relative;overflow:hidden}
footer .ask{display:inline-flex;flex-direction:column;align-items:center;gap:16px}
footer .ask .t{font:400 clamp(28px,8vw,52px)/1.15 var(--serif)}
footer .btn-v{box-shadow:inset 0 0 0 3px var(--verm),inset 0 0 0 4px rgba(255,248,236,.5)}
.fname{font:400 56px/1 var(--serif);letter-spacing:.08em;text-transform:uppercase;color:var(--accent);margin:56px 0 26px}
.fl{display:flex;justify-content:center;flex-wrap:wrap;gap:12px 24px;font:600 10.5px/1 var(--sans);letter-spacing:.2em;text-transform:uppercase;opacity:.8}
.credit{margin-top:24px;font-size:12px;opacity:.6}
/* chrome dress */
.drawer{box-shadow:inset -10px 0 0 -9px var(--accent)}#dnav a{font-family:var(--serif)}#dnav a em{color:var(--atx);opacity:1}
.btn-main{background:var(--verm);color:var(--on-accent)}.btn-main:hover{background:var(--deep)}.btn-alt{border:1px solid var(--ink)}
.lp .gal .ph:first-child{border-radius:0}.lpt{font-family:var(--serif)}.crumb{color:var(--atx)}
.chip{border-color:var(--accent)}.chip:hover,.chip.on{background:var(--verm);border-color:var(--verm);color:#fff}
.emono{border-color:var(--accent)}
@media (min-width:700px){.ml{display:inline}.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}}
@media (min-width:1024px){
 .cover{display:grid;flex-direction:initial;grid-template-columns:1fr 1fr;align-items:center;gap:4vw;text-align:left;padding:30px 6vw 80px;min-height:calc(100vh - 74px)}
 .cover .txt{order:0}.cover .archw{order:1;margin-top:18px;width:min(38vw,560px)}.cover .orn{margin-left:0}.pips{justify-content:flex-start}
 .grid{grid-template-columns:repeat(4,1fr);gap:56px 22px;max-width:1300px;margin:0 auto}.card:nth-child(even){margin-top:70px}
 .craft{aspect-ratio:16/8;max-width:1300px;margin-left:auto;margin-right:auto;border-radius:48% 48% 0 0/70% 70% 0 0}.coll{width:22vw}
 .story{grid-template-columns:1fr 1fr;align-items:center;text-align:left;max-width:1200px;margin:0 auto}.story p,.story .lead{margin-left:0}
}
@media (prefers-reduced-motion:reduce){.jaali{display:none}.rosette{animation:none}.orn path,.orn circle{stroke-dashoffset:0!important}.cover .caps,.cover .btn-v{opacity:1!important;transform:none!important}.row .dots{transform:none!important}}
`;
