// lib/site/styles/noir.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/noir.html sha256 ecf3df22996eb2370efad4f051cd83adcb71dd6eb95fe8192470a2053ca7549c (WEB-3's approved rendition, verbatim).
export const CSS = `
@property --r{syntax:'<percentage>';inherits:false;initial-value:0%}
:root{--bg:#0a0908;--ink:#efe6d6;--mute:#9b9183;--line:rgba(212,178,110,.22);--soft:#16130f;--accent:#d4b26e;--on-accent:#0a0908;
 --g1:#977432;--g2:#e9cf8f;--g3:#b8924a;--gold:linear-gradient(100deg,var(--g1) 0%,var(--g2) 28%,var(--g3) 48%,var(--g2) 70%,var(--g1) 100%);
 --serif:"Italiana","Bodoni Moda",Didot,serif;--sans:"Jost","Futura","Helvetica Neue",sans-serif;--br:0px}
html[data-pal=wine]{--bg:#12070a;--ink:#f2e4e1;--mute:#a58d8e;--soft:#1d0d11;--line:rgba(226,160,150,.22);--accent:#e3a597;--g1:#b6625c;--g2:#f3c3b3;--g3:#c07a6c}
html[data-pal=midnight]{--bg:#060a12;--ink:#e6e9ef;--mute:#8d94a3;--soft:#0e1320;--line:rgba(200,205,220,.2);--accent:#d9d2c0;--g1:#757a89;--g2:#f1ead7;--g3:#aeb2bd}
html[data-font=b]{--serif:"Bodoni Moda",Didot,serif}
.goldtx{background:var(--gold);background-size:220% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:sheen 9s linear infinite}
@keyframes sheen{to{background-position:-220% 0}}
.caps{font:400 10.5px/1.4 var(--sans);letter-spacing:.32em;text-transform:uppercase}
/* grain */
.grain{position:fixed;inset:-50%;z-index:80;pointer-events:none;opacity:.09;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='220'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");animation:grain 1.1s steps(6) infinite;mix-blend-mode:screen}
html[data-grain=off] .grain{display:none}
@keyframes grain{0%{transform:translate(0,0)}20%{transform:translate(-7%,4%)}40%{transform:translate(5%,-6%)}60%{transform:translate(-4%,-3%)}80%{transform:translate(6%,5%)}}
/* header */
.hd{position:fixed;inset:0 0 auto 0;z-index:30;height:64px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 var(--pad);transition:background .6s,backdrop-filter .6s}
.hd.solid{background:color-mix(in srgb,var(--bg) 78%,transparent);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}
.hd .l{justify-self:start;display:flex;gap:10px;align-items:center}.hd .r{justify-self:end;display:flex;gap:14px;align-items:center}
.ml{font:400 10.5px/1 var(--sans);letter-spacing:.3em;text-transform:uppercase;display:none}
.wm{display:flex;justify-content:center;min-width:0;max-width:62vw}
.wmt{font:400 19px/1 var(--serif);letter-spacing:.34em;text-transform:uppercase;white-space:nowrap;padding-left:.34em}
.hd .mono{display:none;border-color:var(--accent);color:var(--accent)}.hd.use-mono .wmt{display:none}.hd.use-mono .mono{display:inline-flex}
.enq{font:400 10.5px/1 var(--sans);letter-spacing:.3em;text-transform:uppercase;padding:9px 0 7px;position:relative}
.enq::after{content:"";position:absolute;left:0;right:.3em;bottom:0;height:1px;background:var(--gold);background-size:200% 100%;animation:sheen 6s linear infinite}
.hd .r .heart{display:none}
/* cover */
.cover{position:relative;height:100svh;min-height:600px;overflow:hidden;background:var(--bg)}
.slide{position:absolute;inset:0;opacity:0}
.slide.on{opacity:1}
.slide img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;--x:50%;--y:40%;
 -webkit-mask-image:radial-gradient(circle at var(--x) var(--y),#000 var(--r),transparent calc(var(--r) + 42%));mask-image:radial-gradient(circle at var(--x) var(--y),#000 var(--r),transparent calc(var(--r) + 42%));
 filter:brightness(.55) contrast(1.08);transform:scale(1.08);transition:--r calc(3.2s * var(--k)) cubic-bezier(.3,.1,.2,1),filter calc(3.4s * var(--k)) ease,transform 9s ease-out}
.slide.lit img{--r:62%;filter:brightness(1) contrast(1.04);transform:scale(1)}
.slide.out img{--r:0%;filter:brightness(.3);transition:--r 1.3s cubic-bezier(.6,0,.8,.4),filter 1.3s ease}
.cover::after{content:"";position:absolute;inset:0;background:linear-gradient(to top,var(--bg) 2%,transparent 45%),linear-gradient(to bottom,rgba(0,0,0,.6),transparent 24%);pointer-events:none}
.cc{position:absolute;z-index:3;left:var(--pad);right:var(--pad);bottom:calc(46px + env(safe-area-inset-bottom,0px));text-align:center}
.cc .caps{color:var(--accent);opacity:0;transition:opacity 1.4s ease .3s}.cover.go .cc .caps{opacity:1}
.ttl{font:400 clamp(44px,13vw,128px)/1 var(--serif);margin:16px 0 18px;letter-spacing:.02em}
.ttl .wd{display:inline-block;white-space:nowrap}.ttl .c{display:inline-block;opacity:0;filter:blur(10px);transform:translateY(.12em);transition:opacity 1.1s ease,filter 1.1s ease,transform 1.1s var(--ease);transition-delay:calc(.5s + var(--i) * 55ms * var(--k))}
.cover.go .ttl .c{opacity:1;filter:none;transform:none}
.rule{width:0;height:1px;margin:0 auto 26px;background:var(--gold);transition:width 1.8s var(--ease) 1.2s}.cover.go .rule{width:120px}
.bg{border:1px solid transparent;background:linear-gradient(var(--bg),var(--bg)) padding-box,var(--gold) border-box;background-size:auto,220% 100%;animation:sheenb 7s linear infinite;color:var(--ink);opacity:0;transition:opacity 1.2s ease 1.6s,color .5s}
@keyframes sheenb{to{background-position:0 0,-220% 0}}
.cover.go .bg{opacity:1}
.bg:hover{background:var(--gold) border-box;color:var(--on-accent)}
.btn.bg::before{display:none}
.dots3{position:absolute;z-index:3;left:50%;transform:translateX(-50%);bottom:18px;display:flex;gap:8px}
.dots3 button{width:26px;height:18px;display:flex;align-items:center}.dots3 i{display:block;width:100%;height:1px;background:rgba(255,255,255,.25);position:relative;overflow:hidden}
.dots3 i::after{content:"";position:absolute;inset:0;background:var(--accent);transform:scaleX(0);transform-origin:left}
.dots3 .run i::after{animation:fill var(--dw,7s) linear both}.dots3 .done i::after{transform:none}
@keyframes fill{to{transform:none}}
/* sections */
section{padding:clamp(56px,13vw,130px) 0 0}
.sh{text-align:center;padding:0 var(--pad);margin-bottom:34px}
.sh h2{font:400 clamp(34px,10vw,76px)/1.04 var(--serif);margin:12px 0 0;letter-spacing:.02em}
.sh .caps{color:var(--accent)}
/* looks: cinematic stack */
.stack{display:flex;flex-direction:column;gap:clamp(48px,12vw,120px);padding:0 var(--pad)}
.card{display:block;position:relative;--e:0}
.card .ph{aspect-ratio:4/5;background:#000}
.card .ph img{filter:brightness(calc(.18 + var(--e) * .9)) saturate(calc(.4 + var(--e) * .7));transform:scale(calc(1.1 - var(--e) * .1));transition:filter .25s linear,transform .25s linear;
 -webkit-mask-image:radial-gradient(ellipse at 50% 45%,#000 calc(20% + var(--e) * 60%),transparent calc(55% + var(--e) * 60%));mask-image:radial-gradient(ellipse at 50% 45%,#000 calc(20% + var(--e) * 60%),transparent calc(55% + var(--e) * 60%))}
.card .n{position:absolute;z-index:2;left:0;top:-12px;font:400 13px/1 var(--serif);letter-spacing:.2em}
.card .meta{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;margin-top:18px}
.card .nm{font:400 clamp(28px,8vw,48px)/1.05 var(--serif);margin:8px 0 6px;letter-spacing:.01em}
.card .pr{color:var(--mute);font:300 13px/1 var(--sans);letter-spacing:.1em}
.card .hbtn{flex:none;border:1px solid var(--line);border-radius:50%;color:var(--accent)}
.card:nth-child(even) .meta{flex-direction:row-reverse;text-align:right}
.card .vidtag{position:absolute;z-index:2;right:12px;top:12px;gap:8px;align-items:center;color:var(--accent);font:400 10px/1 var(--sans);letter-spacing:.24em}
.card .vidtag svg{width:10px;height:10px;fill:currentColor}
/* spotlight room */
.room{position:relative;margin-top:clamp(64px,14vw,140px);height:118vw;max-height:880px;min-height:460px;overflow:hidden;background:#000;touch-action:pan-y;--mx:50%;--my:45%}
.room img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:brightness(1.05)}
.room .dark{position:absolute;inset:0;background:radial-gradient(circle at var(--mx) var(--my),transparent 0,transparent 16%,rgba(0,0,0,.72) 32%,rgba(0,0,0,.97) 52%);pointer-events:none}
.room .lbl{position:absolute;left:0;right:0;bottom:30px;text-align:center;z-index:2;pointer-events:none}
.room .lbl h3{font:400 clamp(30px,9vw,64px)/1.05 var(--serif);margin:10px 0 0}
/* collections */
.rail{display:flex;gap:16px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:0 var(--pad) 6px;scroll-padding:0 var(--pad)}.rail::-webkit-scrollbar{display:none}
.coll{flex:none;width:70vw;max-width:340px;scroll-snap-align:start;position:relative;padding:10px}
.coll svg.fr{position:absolute;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none}
.coll svg.fr rect{fill:none;stroke:url(#goldg);stroke-width:1;stroke-dasharray:2000;stroke-dashoffset:2000;transition:stroke-dashoffset 2.6s var(--ease)}
.coll.in svg.fr rect{stroke-dashoffset:0}
.coll .ph{aspect-ratio:3/4}.coll .ph img{filter:brightness(.8);transition:filter 1s,transform 1.4s var(--ease)}.coll:hover .ph img{filter:brightness(1);transform:scale(1.04)}
.coll .cap{text-align:center;padding:16px 0 6px}.coll .cap b{display:block;font:400 22px/1.2 var(--serif);font-weight:400}.coll .cap span{color:var(--mute);font:300 12px var(--sans);letter-spacing:.14em}
/* reviews */
.rev{padding:0 var(--pad);text-align:center;max-width:820px;margin:0 auto}
.q p{font:400 clamp(26px,7.2vw,46px)/1.25 var(--serif);margin:0 0 22px}
.q .by{color:var(--accent);font:400 10.5px/1.4 var(--sans);letter-spacing:.3em;text-transform:uppercase}
.qnav{display:flex;justify-content:center;gap:22px;align-items:center;margin-top:24px;color:var(--mute);font:400 11px var(--sans);letter-spacing:.2em}
.qnav button{width:44px;height:44px;border:1px solid var(--line);border-radius:50%;display:flex;align-items:center;justify-content:center;color:var(--accent)}
.qnav svg{width:14px;height:14px;stroke:currentColor;fill:none;stroke-width:1.3}
/* pricing */
.price{padding:0 var(--pad);max-width:760px;margin:0 auto}
.row{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:baseline;padding:20px 0;position:relative}
.row::after{content:"";position:absolute;left:0;right:0;bottom:0;height:1px;background:var(--gold);transform:scaleX(0);transform-origin:left;transition:transform 1.4s var(--ease) var(--d,0s);opacity:.55}
.row.in::after{transform:none}
.row .n{font:400 21px/1.25 var(--serif)}.row .v{font:300 13px/1 var(--sans);letter-spacing:.12em;color:var(--accent)}
.note{color:var(--mute);font-size:13px;text-align:center;margin:20px auto 0;max-width:40ch}
/* story */
.story{display:grid;gap:30px;padding:0 var(--pad)}
.story .ph{aspect-ratio:4/5;background:#000}.story .ph img{-webkit-mask-image:radial-gradient(ellipse at 50% 40%,#000 30%,transparent 78%);mask-image:radial-gradient(ellipse at 50% 40%,#000 30%,transparent 78%)}
.story .lead{font:400 clamp(28px,7.6vw,46px)/1.16 var(--serif);margin:12px 0 18px}
.story p{color:var(--mute);margin:0;max-width:46ch}
.faq{padding:0 var(--pad);max-width:760px;margin:0 auto}.fq button{font:400 20px/1.3 var(--serif)}.fq .pm{color:var(--accent)}
/* footer */
footer{margin-top:clamp(80px,16vw,160px);padding:0 var(--pad) calc(90px + env(safe-area-inset-bottom,0px));text-align:center}
.ask{display:inline-flex;flex-direction:column;align-items:center;gap:18px}
.ask .t{font:400 clamp(30px,8.6vw,60px)/1.1 var(--serif)}
.fname{font:400 60px/1 var(--serif);letter-spacing:.06em;text-transform:uppercase;margin:70px 0 28px;white-space:nowrap}
.fl{display:flex;justify-content:center;flex-wrap:wrap;gap:12px 26px;color:var(--mute)}
.credit{margin-top:26px;color:var(--mute);font-size:12px;opacity:.7}
/* chrome, Noir dress */
.drawer{width:100vw;background:var(--bg);transform:none;opacity:0;visibility:hidden;transition:opacity .6s ease,visibility 0s .6s;align-items:center}
.drawer.on{opacity:1;visibility:visible;transition:opacity .6s ease}
.drawer .x{align-self:flex-end;color:var(--accent)}
#dnav{align-items:center;margin-top:8vh}#dnav a{font-size:clamp(34px,9vw,64px);transform:none;filter:blur(8px);transition:opacity .8s ease,filter .8s ease}
.drawer.on #dnav a{filter:none}#dnav a em{display:none}#dnav a:hover{color:var(--accent)}
.dfoot{align-items:center}
.lp{background:var(--bg)}.lp .gal img{animation:emerge 2.2s ease both}
@keyframes emerge{from{filter:brightness(0)}to{filter:brightness(1)}}
.lpt{font-family:var(--serif)}
.btn-main{background:var(--gold) border-box;background-size:220% 100%;color:var(--on-accent);animation:sheen 7s linear infinite}
.btn-alt{border:1px solid var(--line);color:var(--ink)}
.cred a{color:var(--accent)}
.ez{background:var(--soft)}.chip{border-color:var(--line);color:var(--ink)}.chip:hover,.chip.on{background:var(--accent);color:var(--on-accent)}
.m.u{background:rgba(255,255,255,.06)}
.emono{border-color:var(--accent);color:var(--accent)}
@media (min-width:700px){.ml{display:inline}.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}}
@media (min-width:1024px){
 .slide{width:50%;opacity:1}.slide:nth-child(2){left:50%}.slide:nth-child(3){display:none}
 .stack{display:grid;grid-template-columns:1fr 1fr;gap:110px 8vw;max-width:1200px;margin:0 auto}.stack .card:nth-child(even){margin-top:180px}
 .room{height:86vh}.coll{width:26vw}.story{grid-template-columns:5fr 6fr;align-items:center;max-width:1200px;margin:0 auto;gap:6vw}
}
@media (prefers-reduced-motion:reduce){.slide img{--r:80%!important;filter:none!important;transform:none!important}.ttl .c{opacity:1!important;filter:none!important;transform:none!important}.cc .caps,.bg{opacity:1!important}.rule{width:120px!important}.grain{display:none}.card .ph img{filter:none!important;-webkit-mask-image:none!important;mask-image:none!important;transform:none!important}.coll svg.fr rect{stroke-dashoffset:0!important}.row::after{transform:none!important}}
`;
