// lib/site/styles/riviera.css.ts · GENERATED by tools/site_port/port_css.py. Do not edit; edit the source and re-run.
// Source: tools/site_port/riviera.html sha256 c8ddfd60b01d9d898c3603c10271b53775c74432cedd94cbfde444294a0176bf (WEB-3's approved rendition, verbatim).
export const CSS = `
:root{--bg:#f4ede3;--ink:#22343c;--mute:#616d6e;--line:rgba(34,52,60,.15);--soft:#ebe2d4;--accent:#4f8697;--on-accent:#fdfaf4;--sun:#f0c978;--terra:#c8745a;--card:#fffdf8;--deep:#2f5f6e;--on-deep:#f4ede3;--atx:#437180;
 --serif:"Gilda Display","Cormorant Garamond",Georgia,serif;--sans:"Figtree","Helvetica Neue",sans-serif;--quote:var(--serif);--br:999px;--r:4px}
html[data-pal=goa]{--atx:#b4482c;--bg:#f7eee4;--ink:#2c3a2e;--mute:#646e61;--soft:#eee2d2;--accent:#d56f55;--sun:#f3b562;--terra:#4f7a5a;--deep:#3f6b52;--on-deep:#f7eee4}
html[data-pal=santorini]{--atx:#2451a3;--bg:#f6f6f2;--ink:#14305a;--mute:#5f6d85;--soft:#e9eaea;--accent:#2451a3;--sun:#f2d27a;--terra:#2451a3;--deep:#1d3f82;--on-deep:#f6f6f2}
html[data-font=b]{--serif:"Cormorant Garamond",Georgia,serif}
.caps{font:500 10.5px/1.4 var(--sans);letter-spacing:.26em;text-transform:uppercase}
.leak{position:fixed;inset:-30%;z-index:79;pointer-events:none;mix-blend-mode:soft-light;opacity:.55;background:radial-gradient(40% 30% at 30% 30%,var(--sun),transparent 70%),radial-gradient(35% 25% at 75% 70%,#ffd9c2,transparent 70%);animation:leak calc(26s / var(--k)) ease-in-out infinite alternate}
@keyframes leak{to{transform:translate(12%,8%) rotate(8deg)}}
html[data-sun=off] .leak{display:none}
/* header */
.hd{position:fixed;inset:0 0 auto 0;z-index:30;height:62px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 var(--pad);color:#fff;transition:background .6s,color .6s}
.hd.solid{background:color-mix(in srgb,var(--bg) 88%,transparent);color:var(--ink);backdrop-filter:blur(10px)}
.hd .l{justify-self:start;display:flex;gap:8px;align-items:center}.hd .r{justify-self:end;display:flex;gap:14px;align-items:center}
.wmt{font:400 20px/1 var(--serif);letter-spacing:.06em;white-space:nowrap}.hd .mono{display:none}.hd.use-mono .wmt{display:none}.hd.use-mono .mono{display:inline-flex}
.enq{border:1px solid currentColor;border-radius:999px;padding:9px 14px;font:500 11px/1 var(--sans);letter-spacing:.14em;text-transform:uppercase}
.hd .r .heart{display:none}.ml{display:none;font:500 11px var(--sans);letter-spacing:.14em;text-transform:uppercase}
/* cover: slow drone drift */
.cover{position:relative;height:100svh;min-height:600px;overflow:hidden;color:#fff;background:#2e4a52}
.cover img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 0%;animation:drone calc(32s / var(--k)) ease-in-out infinite alternate;transform:scale(1.04)}
@keyframes drone{to{object-position:50% 100%}}
.cover::after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(20,35,40,.6),transparent 50%),linear-gradient(to bottom,rgba(20,35,40,.35),transparent 22%)}
.cc{position:absolute;z-index:2;left:var(--pad);right:var(--pad);bottom:calc(40px + env(safe-area-inset-bottom,0px))}
.cc .caps{opacity:0;transition:opacity 2s ease .4s}.cover.go .cc .caps{opacity:.9}
.h1{font:400 clamp(44px,13.5vw,132px)/1 var(--serif);margin:14px 0 22px;letter-spacing:.005em}
.h1 .ln>span{transition-duration:calc(1.8s * var(--k));transition-timing-function:cubic-bezier(.2,.7,.1,1)}
.btn-p{border:1px solid rgba(255,255,255,.8);color:#fff;opacity:0;transition:opacity 1.6s ease 1.4s,background .5s,color .5s}.cover.go .btn-p{opacity:1}
.btn-p:hover{background:#fff;color:var(--ink)}
.stampc{position:absolute;z-index:2;right:var(--pad);top:calc(84px + env(safe-area-inset-top,0px));width:74px;height:74px;opacity:0;transform:rotate(-14deg) scale(1.3);transition:opacity 1s ease 1.8s,transform 1s cubic-bezier(.3,1.5,.5,1) 1.8s}
.cover.go .stampc{opacity:.9;transform:rotate(-14deg)}
.stampc text{font:500 7px var(--sans);letter-spacing:.2em;fill:#fff}.stampc circle{fill:none;stroke:#fff;stroke-width:.8}
/* destinations drift */
.dest{overflow:hidden;white-space:nowrap;padding:26px 0;border-bottom:1px solid var(--line)}
.dest div{display:inline-block;animation:drift calc(70s / var(--k)) linear infinite;font:400 clamp(24px,6.4vw,40px)/1 var(--serif)}
.dest span{margin:0 18px;color:var(--atx)}
@keyframes drift{to{transform:translateX(-50%)}}
/* sections */
section{padding:clamp(52px,12vw,120px) 0 0}
.sh{padding:0 var(--pad);margin-bottom:28px;text-align:center}
.sh h2{font:400 clamp(32px,9.4vw,76px)/1.05 var(--serif);margin:10px 0 0}
.sh .caps{color:var(--atx)}
/* postcard deck */
.deckw{position:relative;width:100%;aspect-ratio:1/1.18;margin:0 auto;max-width:520px;perspective:1200px;touch-action:pan-y}   /* the stack's box holds the card's real height */
.pc{position:absolute;left:10%;right:10%;top:4%;aspect-ratio:3/4;background:var(--card);padding:10px 10px 44px;box-shadow:0 18px 36px -18px rgba(40,50,50,.45),0 2px 6px rgba(40,50,50,.12);border-radius:var(--r);
 transform:translate(var(--tx,0),var(--ty,0)) rotate(var(--rot,0deg));transition:transform .9s cubic-bezier(.2,.8,.2,1),opacity .6s;cursor:grab;user-select:none}
.pc .ph{position:absolute;left:10px;right:10px;top:10px;bottom:44px;border-radius:2px}
.pc .pcap{position:absolute;left:14px;right:14px;bottom:12px;display:flex;justify-content:space-between;align-items:center;font:400 15px/1 var(--serif);color:var(--ink)}
.pc .pcap small{font:500 11px var(--sans);color:var(--mute);letter-spacing:.06em}
.pc .stamp{position:absolute;right:18px;top:18px;width:46px;height:56px;background:var(--card);padding:4px;z-index:2;-webkit-mask:radial-gradient(circle 3px at 3px 3px,transparent 97%,#000) -3px -3px/7px 7px;mask:radial-gradient(circle 3px at 3px 3px,transparent 97%,#000) -3px -3px/7px 7px}
.pc .stamp i{display:block;width:100%;height:100%;background:var(--accent);opacity:.85}
.pc .pm{position:absolute;right:44px;top:44px;width:60px;height:60px;z-index:2;opacity:.8}.pc .pm circle{fill:none;stroke:var(--ink);stroke-width:.8}.pc .pm text{font:500 6.5px var(--sans);letter-spacing:.16em;fill:var(--ink)}
.pc:not(:last-child) .pcap,.pc:not(:last-child) .pm{opacity:0;transition:opacity .3s}   /* only the top postcard speaks; cards beneath show their photographs only */
.pc.fly{transform:translate(var(--fx,140%),-6%) rotate(var(--fr,24deg))!important;opacity:0}
.deckcap{text-align:center;padding:14px var(--pad) 0}
.deckcap .nm{font:400 24px/1.2 var(--serif);min-height:1.2em}.deckcap .pr{color:var(--mute);font-size:13px;margin:4px 0 14px}
.deckbtns{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}
.btn-s{border:1px solid var(--ink);color:var(--ink)}.btn-s:hover{background:var(--ink);color:var(--bg)}
.btn-f{background:var(--atx);color:var(--on-accent)}
.hint2{text-align:center;color:var(--mute);font-size:12px;margin-top:12px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:26px 14px;padding:36px var(--pad) 0}
.card{display:block;background:var(--card);padding:7px 7px 12px;box-shadow:0 10px 24px -14px rgba(40,50,50,.4);transform:rotate(var(--rt));transition:transform .6s var(--ease)}
.card:hover{transform:rotate(0) translateY(-4px)}
.card .ph{aspect-ratio:4/5}.card .nm{font:400 15px/1.25 var(--serif);margin:9px 2px 2px}.card .pr{font-size:11.5px;color:var(--mute);margin:0 2px}
.card .hbtn{position:absolute;right:8px;top:8px;width:36px;height:36px;border-radius:50%;background:rgba(255,253,248,.85);z-index:2}
.card .vidtag{position:absolute;z-index:2;left:12px;top:12px;background:rgba(255,253,248,.9);border-radius:999px;padding:5px 9px;gap:6px;align-items:center;font:500 10.5px var(--sans)}
.card .vidtag svg{width:9px;height:9px;fill:currentColor}
/* slow band */
.slow{position:relative;margin-top:clamp(60px,13vw,130px);height:100vw;max-height:720px;min-height:420px;overflow:hidden;color:#fff}
.slow img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;animation:pan calc(40s / var(--k)) ease-in-out infinite alternate}
@keyframes pan{from{object-position:0% 50%;transform:scale(1.05)}to{object-position:100% 50%;transform:scale(1.12)}}
.slow::after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(20,35,40,.55),transparent 55%)}
.slow .in2{position:absolute;z-index:2;left:var(--pad);right:var(--pad);bottom:34px}
.slow h3{font:400 clamp(30px,9vw,70px)/1.05 var(--serif);margin:10px 0 0}
/* collections as a travel rail */
.rail{display:flex;gap:14px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:6px var(--pad) 14px;scroll-padding:0 var(--pad)}.rail::-webkit-scrollbar{display:none}
.coll{flex:none;width:66vw;max-width:320px;scroll-snap-align:start}
.coll .ph{aspect-ratio:3/4;border-radius:160px 160px 4px 4px}
.coll b{display:block;font:400 21px/1.2 var(--serif);font-weight:400;margin-top:12px}.coll span{color:var(--mute);font-size:12.5px}
/* reviews: a note on a card */
.note-card{margin:0 var(--pad);background:var(--card);padding:28px 22px 22px;box-shadow:0 18px 36px -20px rgba(40,50,50,.4);transform:rotate(-1deg);max-width:760px;position:relative;background-image:repeating-linear-gradient(transparent 0 33px,var(--line) 33px 34px);background-position:0 24px}
@media (min-width:808px){.note-card{margin:0 auto}}
.q p{font:italic 400 clamp(25px,7vw,40px)/34px var(--quote);margin:0 0 16px}
.q .by{font:500 11.5px var(--sans);color:var(--mute);letter-spacing:.06em}
.qnav{display:flex;gap:16px;margin-top:14px;font:500 11px var(--sans);letter-spacing:.14em;text-transform:uppercase}.qnav button{border-bottom:1px solid currentColor;padding:6px 0}
/* rates */
.rates{margin:0 var(--pad);max-width:720px;border-top:1px solid var(--ink)}
@media (min-width:768px){.rates{margin:0 auto}}
.row{display:flex;justify-content:space-between;gap:14px;align-items:baseline;padding:17px 0;border-bottom:1px solid var(--line)}
.row .n{font:400 19px/1.3 var(--serif)}.row .v{font:500 12.5px var(--sans);color:var(--atx);white-space:nowrap}
.note{color:var(--mute);font-size:13px;margin:14px 0 0;text-align:center}
.story{padding:0 var(--pad);display:grid;gap:24px}.story .ph{aspect-ratio:4/5;border-radius:200px 200px 4px 4px}
.story .lead{font:400 clamp(26px,7.4vw,46px)/1.15 var(--serif);margin:10px 0 14px}.story p{color:var(--mute);max-width:44ch;margin:0}
.faq{padding:0 var(--pad);max-width:760px;margin:0 auto}.fq button{font:400 19px/1.3 var(--serif)}
footer{margin-top:clamp(64px,13vw,130px);background:var(--deep);color:var(--on-deep);padding:56px var(--pad) calc(96px + env(safe-area-inset-bottom,0px));text-align:center;position:relative;overflow:hidden}
footer .sun{position:absolute;left:50%;top:-80px;width:220px;height:220px;border-radius:50%;background:radial-gradient(circle,var(--sun),transparent 70%);transform:translateX(-50%);opacity:.5}
footer .t{font:400 clamp(30px,8.6vw,60px)/1.1 var(--serif);display:block;margin:10px 0 20px;position:relative}
footer .btn{border:1px solid var(--on-deep);color:var(--on-deep)}
.fname{font:400 60px/1 var(--serif);white-space:nowrap;margin:54px 0 20px;opacity:.95}
.fl{display:flex;justify-content:center;flex-wrap:wrap;gap:10px 22px;font:500 11px/1 var(--sans);letter-spacing:.16em;text-transform:uppercase;opacity:.8}.credit{margin-top:22px;font-size:12px;opacity:.6}
/* chrome dress */
.btn{letter-spacing:.14em}.btn-main{background:var(--atx);color:var(--on-accent)}.btn-alt{border:1px solid var(--ink)}
.lpt{font-family:var(--serif)}.crumb{color:var(--atx)}.drawer{background:var(--bg)}#dnav a em{color:var(--atx);opacity:1}
.chip{border-color:var(--atx);color:var(--ink)}.chip:hover,.chip.on{background:var(--atx);color:var(--on-accent)}
.m.s{font-family:var(--serif)}
@media (min-width:700px){.ml{display:inline}.hd .l .heart{display:none}.hd .r .heart{display:inline-flex}}
@media (min-width:1024px){
 .cover img{object-position:50% 50%;animation-name:dronew}@keyframes dronew{from{transform:scale(1.04) translateY(-2%)}to{transform:scale(1.14) translateY(2%)}}
 .looksw{display:grid;grid-template-columns:1fr 1.2fr;align-items:center;gap:4vw;max-width:1300px;margin:0 auto;padding:0 4vw}
 .grid{grid-template-columns:repeat(4,1fr);max-width:1300px;margin:0 auto;gap:40px 26px}.coll{width:24vw}
 .story{grid-template-columns:1fr 1fr;align-items:center;max-width:1200px;margin:0 auto}.slow{max-height:80vh;height:80vh}
}
@media (prefers-reduced-motion:reduce){.cover img,.slow img,.dest div,.leak{animation:none!important}.cc .caps,.btn-p,.stampc{opacity:1!important;transform:rotate(-14deg)!important}}
`;
